//
//  toolkit/price-drop/logging-actions
//  Project-Lego
//
//  Created by Yuqing He on 12/03/19.
//  Copyright © 2019-present ContextLogic Inc. All rights reserved.
//

export const PriceDropLoggingActions = {
  // Price Drop page overall:
  FIRST_TIME_MODAL_IMPRESSION: "FIRST_TIME_MODAL_IMPRESSION",
  CLICK_FIRST_TIME_MODAL_SELECT_ALL_TO_DROP:
    "CLICK_FIRST_TIME_MODAL_SELECT_ALL_TO_DROP",

  // Trial Price Drop page actions:
  TRIAL_PRICE_DROP_PAGE_IMPRESSION: "TRIAL_PRICE_DROP_PAGE_IMPRESSION",
  CLICK_DROP_PRICE_FROM_TRIAL_PRICE_DROP:
    "CLICK_DROP_PRICE_FROM_TRIAL_PRICE_DROP",
  CLICK_BATCH_DROP_PRICE: "CLICK_BATCH_DROP_PRICE",
  CLICK_RESET_FROM_TRIAL_PRICE_DROP: "CLICK_RESET_FROM_TRIAL_PRICE_DROP",
  CLICK_EXPANDABLE_SECTION_FOR_TRIAL_PERFORMANCE:
    "CLICK_EXPANDABLE_SECTION_FOR_TRIAL_PERFORMANCE",

  // Pending Campaigns page actions:
  PENDING_CAMPAIGN_PAGE_IMPRESSION: "PENDING_CAMPAIGN_PAGE_IMPRESSION",
  CANCEL_PENDING_PRICE_DROP_CAMPAIGN: "CANCEL_PENDING_PRICE_DROP_CAMPAIGN",

  // Ongoing Campaigns page actions:
  CLICK_REISSUE_PRICE_DROP: "CLICK_REISSUE_PRICE_DROP",
  ONGOING_CAMPAIGN_PAGE_IMPRESSION: "ONGOING_CAMPAIGN_PAGE_IMPRESSION",
  TOGGLE_ON_AUTO_RENEW_FROM_ONGOING_CAMPAIGN:
    "TOGGLE_ON_AUTO_RENEW_FROM_ONGOING_CAMPAIGN",
  TOGGLE_OFF_AUTO_RENEW_FROM_ONGOING_CAMPAIGN:
    "TOGGLE_OFF_AUTO_RENEW_FROM_ONGOING_CAMPAIGN",
  CLICK_EXPANDABLE_SECTION_FOR_ONGOING_PERFORMANCE:
    "CLICK_EXPANDABLE_SECTION_FOR_ONGOING_PERFORMANCE",

  // History page actions:
  HISTORY_CAMPAIGN_PAGE_IMPRESSION: "HISTORY_CAMPAIGN_PAGE_IMPRESSION",

  // PriceDrop performance page actions:
  PRICE_DROP_PERFORMANCE_PAGE_IMPRESSION:
    "PRICE_DROP_PERFORMANCE_PAGE_IMPRESSION",
  CLICK_DROP_PRICE_FROM_PERFORMANCE_PAGE:
    "CLICK_DROP_PRICE_FROM_PERFORMANCE_PAGE",
  CLICK_RESET_FROM_PERFORMANCE_PAGE: "CLICK_RESET_FROM_PERFORMANCE_PAGE",
  TOGGLE_ON_AUTO_RENEW_FROM_PERFORMANCE_PAGE:
    "TOGGLE_ON_AUTO_RENEW_FROM_PERFORMANCE_PAGE",
  TOGGLE_OFF_AUTO_RENEW_FROM_PERFORMANCE_PAGE:
    "TOGGLE_OFF_AUTO_RENEW_FROM_PERFORMANCE_PAGE",

  // Create price drop campaign page:
  CREATE_PRICE_DROP_CAMPAIGN_PAGE_IMPRESSION:
    "CREATE_PRICE_DROP_CAMPAIGN_PAGE_IMPRESSION",
  CLICK_CREATE_PRICE_DROP_CAMPAIGN: "CLICK_CREATE_PRICE_DROP_CAMPAIGN",
  TOGGLE_ON_AUTO_RENEW_FROM_CREATION_PAGE:
    "TOGGLE_ON_AUTO_RENEW_FROM_CREATION_PAGE",
  TOGGLE_OFF_AUTO_RENEW_FROM_CREATION_PAGE:
    "TOGGLE_OFF_AUTO_RENEW_FROM_CREATION_PAGE",
};
