stages:
  - schedule
  - install
  - test
  - deploy

variables:
  MANUAL_EXTRACT_STRINGS: ""

include:
  - local: /pipeline/i18n/gitlab-ci.i18n.yml

install dependencies:
  stage: install
  image: registry-gitlab.i.wish.com/contextlogic/leopard/node:18
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: registry-gitlab.i.wish.com/contextlogic/leopard/node:18
  script:
    - yarn test-ci
  dependencies:
    - install dependencies

lint:
  stage: test
  image: registry-gitlab.i.wish.com/contextlogic/leopard/node:18
  script:
    - yarn lint
    - yarn graphql-codegen --overwrite --verbose
    - git diff --exit-code
  dependencies:
    - install dependencies

build staging:
  stage: test
  image: registry-gitlab.i.wish.com/contextlogic/leopard/node:18
  script:
    # we want the `development` configs on staging, even though we are optimizing the build for prod
    - cp .env.development .env.production
    - yarn build
  artifacts:
    when: always
    paths:
      - out
  dependencies:
    - install dependencies

build prod:
  stage: test
  image: registry-gitlab.i.wish.com/contextlogic/leopard/node:18
  script:
    - yarn build
  artifacts:
    when: always
    paths:
      - out
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - install dependencies

deploy staging:
  stage: deploy
  image: registry-gitlab.i.wish.com/contextlogic/leopard/aws-base-with-brotli:latest
  script:
    - sh scripts/deploy.sh -s=leopard-staging
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: manual
      allow_failure: true
  tags: [leopard-staging]
  dependencies:
    - build staging

deploy prod:
  stage: deploy
  image: registry-gitlab.i.wish.com/contextlogic/leopard/aws-base-with-brotli:latest
  script:
    - sh scripts/deploy.sh -s=leopard-production
  environment:
    name: production
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags: [leopard]
  dependencies:
    - build prod
#
# temp disabling lighthouse so we can remove docker - will re-write at a later date
# include:
#   - project: "contextlogic/includes"
#     ref: master
#     file: "/templates/job-build-and-tag/ecr-commit.yml"
#   - local: "pipeline/schedule.yml"
#   - local: "pipeline/test.yml"
