variables:
  ITA_TEMPLATE: default-service # DO NOT change this
  ITA_ADD_BUILD_ARGS: "ITA_JOB_TOKEN ITA_PROJECT_NAME"

stages:
  - pre-test
  - build
  - test
  - tag
  - release

include:
  - project: "contextlogic/includes"
    ref: master
    file: "/templates/job-build-tag-and-deploy/default.yml"

# Note for customized jobs, please use the Gitlab rules syntax instead of only/except.
# Gitlab rules - https://docs.gitlab.com/ee/ci/yaml/#rules


# Below is an example of integration test
# Please note this is only for reference, you should always write your own integration tests.

# integration-test:
#   stage: test
#   services: # For knowledge on services - https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
#     - name: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
#       alias: default-service-ci
#       command:
#         - python3
#         - app/server.py
#   image: registry-gitlab.i.wish.com/contextlogic/tooling-image/python/master
#   script:
#     # These scripts should be replaced with actual tests that validate the expected logic
#     - curl -X GET http://default-service-ci:8080/
