image: registry-gitlab.i.wish.com/contextlogic/tooling-image/node:16-alpine3.11

variables:
  ITA_TEMPLATE: default-service # DO NOT change this
  ITA_ADD_BUILD_ARGS: "ITA_JOB_TOKEN ITA_PROJECT_NAME"

stages:
  - schedule
  - pre-test
  - build
  - test
  - tag
  - deploy_staging
  - deploy_production

install_dependencies:
  stage: pre-test
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
  except:
    - schedules

include:
  - project: "contextlogic/includes"
    ref: master
    file: "/templates/job-build-and-tag/ecr-commit.yml"
  - local: 'pipeline/schedule.yml'
  - local: 'pipeline/test.yml'
  - local: 'pipeline/build.yml'
  - local: 'pipeline/deploy.yml'