stages:
  - schedule
  - install
  - build
  # temp disabling lighthouse so we can remove docker - will re-write at a later date
  # - test
  - deploy

install_dependencies:
  stage: install
  image: node:16
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
  except:
    - schedules

build:
  stage: build
  image: node:16
  script:
    - yarn build
  artifacts:
    when: always
    paths:
      - out

deploy_staging:
  stage: deploy
  image: registry-gitlab.i.wish.com/contextlogic/leopard/aws-base:latest
  script:
    - sh scripts/deploy.sh -s=leopard-staging -c=E1SMAHICCX1GPQ
  environment:
    name: staging
  when: manual
  tags: [leopard-staging]

deploy_prod:
  stage: deploy
  image: registry-gitlab.i.wish.com/contextlogic/leopard/aws-base:latest
  script:
    - sh scripts/deploy.sh -s=leopard-production -c=E1SMAHICCX1GPQ
  environment:
    name: production
  when: manual
  tags: [leopard]
# temp disabling lighthouse so we can remove docker - will re-write at a later date
# include:
#   - project: "contextlogic/includes"
#     ref: master
#     file: "/templates/job-build-and-tag/ecr-commit.yml"
#   - local: "pipeline/schedule.yml"
#   - local: "pipeline/test.yml"
