export type WishExpressLoggingAction =
  | "CLICK_LEARN_MORE_HOME_PAGE"
  | "CLICK_LEARN_MORE_PRODUCTS_PAGE"
  | "CLICK_INTRO_MODAL_DONE"
  | "CLICK_WISH_EXPRESS_MASTER_CHECKBOX"
  | "CLICK_WISH_EXPRESS_COUNTRY_CHECKBOX";
