import wishLogoInkURL from "public/images/wish-logo-ink.svg";
import wishLogoWhiteURL from "public/images/wish-logo-white.svg";
import merchantLogoWhiteCNURL from "public/images/merchant-logo/merchant-logo-white-cn.svg";
import merchantLogoCNURL from "public/images/merchant-logo/merchant-logo-cn.svg";
import merchantLogoWhiteCZURL from "public/images/merchant-logo/merchant-logo-white-cz.svg";
import merchantLogoCZURL from "public/images/merchant-logo/merchant-logo-cz.svg";
import merchantLogoWhiteDEURL from "public/images/merchant-logo/merchant-logo-white-de.svg";
import merchantLogoDEURL from "public/images/merchant-logo/merchant-logo-de.svg";
import merchantLogoWhiteESURL from "public/images/merchant-logo/merchant-logo-white-es.svg";
import merchantLogoESURL from "public/images/merchant-logo/merchant-logo-es.svg";
import merchantLogoWhiteFRURL from "public/images/merchant-logo/merchant-logo-white-fr.svg";
import merchantLogoFRURL from "public/images/merchant-logo/merchant-logo-fr.svg";
import merchantLogoWhiteITURL from "public/images/merchant-logo/merchant-logo-white-it.svg";
import merchantLogoITURL from "public/images/merchant-logo/merchant-logo-it.svg";
import merchantLogoWhiteJPURL from "public/images/merchant-logo/merchant-logo-white-jp.svg";
import merchantLogoJPURL from "public/images/merchant-logo/merchant-logo-jp.svg";
import merchantLogoWhiteKRURL from "public/images/merchant-logo/merchant-logo-white-kr.svg";
import merchantLogoKRURL from "public/images/merchant-logo/merchant-logo-kr.svg";
import merchantLogoWhiteNLURL from "public/images/merchant-logo/merchant-logo-white-nl.svg";
import merchantLogoNLURL from "public/images/merchant-logo/merchant-logo-nl.svg";
import merchantLogoWhitePTURL from "public/images/merchant-logo/merchant-logo-white-pt.svg";
import merchantLogoPTURL from "public/images/merchant-logo/merchant-logo-pt.svg";
import merchantLogoWhiteSEURL from "public/images/merchant-logo/merchant-logo-white-se.svg";
import merchantLogoSEURL from "public/images/merchant-logo/merchant-logo-se.svg";
import merchantLogoWhiteTRURL from "public/images/merchant-logo/merchant-logo-white-tr.svg";
import merchantLogoTRURL from "public/images/merchant-logo/merchant-logo-tr.svg";
import merchantLogoWhiteVNURL from "public/images/merchant-logo/merchant-logo-white-vn.svg";
import merchantLogoVNURL from "public/images/merchant-logo/merchant-logo-vn.svg";
import merchantLogoWhiteENURL from "public/images/merchant-logo/merchant-logo-white-en.svg";
import merchantLogoENURL from "public/images/merchant-logo/merchant-logo-en.svg";

import mmsWelcomeBusinessIntelligenceURL from "public/images/mms-welcome/mms-welcome-business-intelligence.svg";
import mmsWelcomeContentCreationURL from "public/images/mms-welcome/mms-welcome-content-creation.svg";
import mmsWelcomeCustomerServiceURL from "public/images/mms-welcome/mms-welcome-customer-service.svg";
import mmsWelcomeDesktopURL from "public/images/mms-welcome/mms-welcome-desktop.svg";
import mmsWelcomeInventoryManagementURL from "public/images/mms-welcome/mms-welcome-inventory-management.svg";
import mmsWelcomeLaptopSurveyURL from "public/images/mms-welcome/mms-welcome-laptop-survey.svg";
import mmsWelcomeListingURL from "public/images/mms-welcome/mms-welcome-listing.svg";
import mmsWelcomeLogisticsURL from "public/images/mms-welcome/mms-welcome-logistics.svg";
import mmsWelcomePencilURL from "public/images/mms-welcome/mms-welcome-pencil.svg";
import mmsWelcomePricingAdviceURL from "public/images/mms-welcome/mms-welcome-pricing-advice.svg";
import mmsWelcomeProductVerificationURL from "public/images/mms-welcome/mms-welcome-product-verification.svg";
import mmsWelcomeStoreSetupURL from "public/images/mms-welcome/mms-welcome-store-setup.svg";
import mmsWelcomeSuccessBannerURL from "public/images/mms-welcome/mms-welcome-success-banner.svg";
import mmsWelcomeTicketsCoinsURL from "public/images/mms-welcome/mms-welcome-tickets-coins.svg";
import mmsWelcomeTreeURL from "public/images/mms-welcome/mms-welcome-tree.svg";
import mmsWelcomeTruckURL from "public/images/mms-welcome/mms-welcome-truck.svg";
import mmsWelcomeUserTrafficURL from "public/images/mms-welcome/mms-welcome-user-traffic.svg";

import homeSelectedURL from "public/images/side-menu-icons/home-selected.svg";
import homeNotSelectedURL from "public/images/side-menu-icons/home-not-selected.svg";
import ordersSelectedURL from "public/images/side-menu-icons/orders-selected.svg";
import ordersNotSelectedURL from "public/images/side-menu-icons/orders-not-selected.svg";
import pbSelectedURL from "public/images/side-menu-icons/pb-selected.svg";
import pbNotSelectedURL from "public/images/side-menu-icons/pb-not-selected.svg";
import performanceSelectedURL from "public/images/side-menu-icons/performance-selected.svg";
import performanceNotSelectedURL from "public/images/side-menu-icons/performance-not-selected.svg";
import productsSelectedURL from "public/images/side-menu-icons/products-selected.svg";
import productsNotSelectedURL from "public/images/side-menu-icons/products-not-selected.svg";
import ticketsSelectedURL from "public/images/side-menu-icons/tickets-selected.svg";
import ticketsNotSelectedURL from "public/images/side-menu-icons/tickets-not-selected.svg";
import infractionsSelectedURL from "public/images/side-menu-icons/infractions-selected.svg";
import infractionsNotSelectedURL from "public/images/side-menu-icons/infractions-not-selected.svg";
import fbwFbsSelectedURL from "public/images/side-menu-icons/fbw-fbs-selected.svg";
import fbwFbsNotSelectedURL from "public/images/side-menu-icons/fbw-fbs-not-selected.svg";
import earlyPaymentSelectedURL from "public/images/side-menu-icons/early-payment-selected.svg";
import earlyPaymentNotSelectedURL from "public/images/side-menu-icons/early-payment-not-selected.svg";

import shippingPriceDropURL from "public/images/welcome-invite-only/shipping-price-drop.svg";
import manCheeringURL from "public/images/welcome-invite-only/man-cheering.svg";
import landingHeaderIllustrationLeftURL from "public/images/welcome-invite-only/landing-header-illustration-left.svg";
import landingHeaderIllustrationRightURL from "public/images/welcome-invite-only/landing-header-illustration-right.svg";
import landingHeaderIllustrationSmallerURL from "public/images/welcome-invite-only/landing-header-illustration-smaller.svg";
import globePhoneLocationsURL from "public/images/welcome-invite-only/globe-phone-locations.svg";

import brandedURL from "public/images/product-badges/branded.svg";
import wishExpressURL from "public/images/product-badges/wish-express.svg";
import yellowBadgeURL from "public/images/product-badges/yellow-badge.svg";
import cleanImageURL from "public/images/product-badges/clean-image.svg";
import returnEnrolledURL from "public/images/product-badges/return-enrolled.svg";
import clockCircleArrowURL from "public/images/clock-circle-arrow.svg";

import error403URL from "public/images/error-403.svg";
import error404URL from "public/images/error-404.svg";
import error500URL from "public/images/error-500.svg";

import bannerUploadProductsURL from "public/images/home/banner-upload-products.svg";
import bannerAddProductVariationsURL from "public/images/home/banner-add-product-variations.svg";
import ladyHoldingPackageURL from "public/images/home/lady-holding-package.svg";
import starFilledURL from "public/images/home/star-filled.svg";
import starHalfFilledURL from "public/images/home/star-half-filled.svg";
import starUnfilledURL from "public/images/home/star-unfilled.svg";
import announcementBadgeAdvancedLogisticsProgramURL from "public/images/home/announcement-icons/advanced-logistics-program.svg";
import announcementBadgeEpcURL from "public/images/home/announcement-icons/epc.svg";
import announcementBadgeFbwURL from "public/images/home/announcement-icons/fbw.svg";
import announcementBadgeMerchantFundedPromotionsURL from "public/images/home/announcement-icons/merchant-funded-promotions.svg";
import announcementBadgePlatinumURL from "public/images/home/announcement-icons/platinum.svg";
import announcementBadgeProductBoostURL from "public/images/home/announcement-icons/product-boost.svg";
import announcementBadgeRefundsURL from "public/images/home/announcement-icons/refunds.svg";
import announcementBadgeReturnsURL from "public/images/home/announcement-icons/returns.svg";
import announcementBadgeVideosURL from "public/images/home/announcement-icons/videos.svg";
import announcementBadgeWishExpressBlueBoxURL from "public/images/home/announcement-icons/wish-express-blue-box.svg";
import announcementBadgeWishPostURL from "public/images/home/announcement-icons/wish-post.svg";
import announcementBadgeWishStandardsURL from "public/images/home/announcement-icons/wish-standards.svg";
import homePbModalBudgetURL from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-budget.svg";
import homePbModalFbwDiscountURL from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-fbw-discount.svg";
import homePbModalLogoURL from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-logo.svg";
import homePbModalRefundAssuranceURL from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-refund-assurance.svg";
import homePbModalRocketURL from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-rocket.png";
import homeFrsOptInModalURL from "public/images/home/announcement-modal/home-frs-opt-in-modal.svg";

import bannerBackToOnboardingURL from "public/images/home/banner-images/banner-back-to-onboarding.svg";
import bannerCustomerSupportURL from "public/images/home/banner-images/banner-customer-support.svg";
import bannerMerchantBlogURL from "public/images/home/banner-images/banner-merchant-blog.svg";
import bannerMfpURL from "public/images/home/banner-images/banner-mfp.svg";
import bannerOnboardingReviewURL from "public/images/home/banner-images/banner-onboarding-review.svg";
import bannerProductBoostAutomatedCampaignURL from "public/images/home/banner-images/banner-product-boost-automated-campaign.svg";
import bannerPbSeasonalBlackFridayURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-black-friday.png";
import bannerPbSeasonalChineseNewYearURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-chinese-new-year.svg";
import bannerPbSeasonalCovidURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-covid.svg";
import bannerPbSeasonalDefaultURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-default.svg";
import bannerPbSeasonalEasterURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-easter.svg";
import bannerPbSeasonalHalloweenURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-halloween.svg";
import bannerPbSeasonalIncreaseBudgetURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-increase-budget.svg";
import bannerPbSeasonalJulyURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-july.svg";
import bannerPbSeasonalMayHighDemandURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-may-high-demand.svg";
import bannerPbSeasonalMothersDayURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-mothers-day.svg";
import bannerPbSeasonalPreHolidayURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-pre-holiday.svg";
import bannerPbSeasonalSinglesDayURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-singles-day.svg";
import bannerPbSeasonalSummerURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-summer.svg";
import bannerPbSeasonalThanksgivingURL from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-thanksgiving.svg";
import bannerSellerProfileURL from "public/images/home/banner-images/banner-seller-profile.svg";
import bannerWeeklyDisbUpgradeURL from "public/images/home/banner-images/banner-weekly-disb-upgrade.svg";
import bannerWishClipsURL from "public/images/home/banner-images/banner-wish-clips.png";

import todoDeclineTaxSettingsURL from "public/images/home/todo/todo-decline-tax-settings.svg";
import todoWishExpressWithTextURL from "public/images/home/todo/todo-wish-express-with-text.svg";

import topSellerURL from "public/images/top-seller.svg";
import wishExpressTruckURL from "public/images/wish-express.svg";
import emptyImageURL from "public/images/emptyimage.svg";
import authenticBrandSellerBadgeURL from "public/images/authentic_brand_seller_badge.svg";
import mockMobileHeaderURL from "public/images/mock-mobile-header.png";

export const wishLogoInk = wishLogoInkURL;
export const wishLogoWhite = wishLogoWhiteURL;
export const merchantLogoWhiteCN = merchantLogoWhiteCNURL;
export const merchantLogoCN = merchantLogoCNURL;
export const merchantLogoWhiteCZ = merchantLogoWhiteCZURL;
export const merchantLogoCZ = merchantLogoCZURL;
export const merchantLogoWhiteDE = merchantLogoWhiteDEURL;
export const merchantLogoDE = merchantLogoDEURL;
export const merchantLogoWhiteES = merchantLogoWhiteESURL;
export const merchantLogoES = merchantLogoESURL;
export const merchantLogoWhiteFR = merchantLogoWhiteFRURL;
export const merchantLogoFR = merchantLogoFRURL;
export const merchantLogoWhiteIT = merchantLogoWhiteITURL;
export const merchantLogoIT = merchantLogoITURL;
export const merchantLogoWhiteJP = merchantLogoWhiteJPURL;
export const merchantLogoJP = merchantLogoJPURL;
export const merchantLogoWhiteKR = merchantLogoWhiteKRURL;
export const merchantLogoKR = merchantLogoKRURL;
export const merchantLogoWhiteNL = merchantLogoWhiteNLURL;
export const merchantLogoNL = merchantLogoNLURL;
export const merchantLogoWhitePT = merchantLogoWhitePTURL;
export const merchantLogoPT = merchantLogoPTURL;
export const merchantLogoWhiteSE = merchantLogoWhiteSEURL;
export const merchantLogoSE = merchantLogoSEURL;
export const merchantLogoWhiteTR = merchantLogoWhiteTRURL;
export const merchantLogoTR = merchantLogoTRURL;
export const merchantLogoWhiteVN = merchantLogoWhiteVNURL;
export const merchantLogoVN = merchantLogoVNURL;
export const merchantLogoWhiteEN = merchantLogoWhiteENURL;
export const merchantLogoEN = merchantLogoENURL;
export const mmsWelcomeBusinessIntelligence = mmsWelcomeBusinessIntelligenceURL;
export const mmsWelcomeContentCreation = mmsWelcomeContentCreationURL;
export const mmsWelcomeCustomerService = mmsWelcomeCustomerServiceURL;
export const mmsWelcomeDesktop = mmsWelcomeDesktopURL;
export const mmsWelcomeInventoryManagement = mmsWelcomeInventoryManagementURL;
export const mmsWelcomeLaptopSurvey = mmsWelcomeLaptopSurveyURL;
export const mmsWelcomeListing = mmsWelcomeListingURL;
export const mmsWelcomeLogistics = mmsWelcomeLogisticsURL;
export const mmsWelcomePencil = mmsWelcomePencilURL;
export const mmsWelcomePricingAdvice = mmsWelcomePricingAdviceURL;
export const mmsWelcomeProductVerification = mmsWelcomeProductVerificationURL;
export const mmsWelcomeStoreSetup = mmsWelcomeStoreSetupURL;
export const mmsWelcomeSuccessBanner = mmsWelcomeSuccessBannerURL;
export const mmsWelcomeTicketsCoins = mmsWelcomeTicketsCoinsURL;
export const mmsWelcomeTree = mmsWelcomeTreeURL;
export const mmsWelcomeTruck = mmsWelcomeTruckURL;
export const mmsWelcomeUserTraffic = mmsWelcomeUserTrafficURL;
export const homeSelected = homeSelectedURL;
export const homeNotSelected = homeNotSelectedURL;
export const ordersSelected = ordersSelectedURL;
export const ordersNotSelected = ordersNotSelectedURL;
export const pbSelected = pbSelectedURL;
export const pbNotSelected = pbNotSelectedURL;
export const performanceSelected = performanceSelectedURL;
export const performanceNotSelected = performanceNotSelectedURL;
export const productsSelected = productsSelectedURL;
export const productsNotSelected = productsNotSelectedURL;
export const ticketsSelected = ticketsSelectedURL;
export const ticketsNotSelected = ticketsNotSelectedURL;
export const infractionsSelected = infractionsSelectedURL;
export const infractionsNotSelected = infractionsNotSelectedURL;
export const fbwFbsSelected = fbwFbsSelectedURL;
export const fbwFbsNotSelected = fbwFbsNotSelectedURL;
export const earlyPaymentSelected = earlyPaymentSelectedURL;
export const earlyPaymentNotSelected = earlyPaymentNotSelectedURL;
export const shippingPriceDrop = shippingPriceDropURL;
export const manCheering = manCheeringURL;
export const landingHeaderIllustrationLeft = landingHeaderIllustrationLeftURL;
export const landingHeaderIllustrationRight = landingHeaderIllustrationRightURL;
export const landingHeaderIllustrationSmaller =
  landingHeaderIllustrationSmallerURL;
export const globePhoneLocations = globePhoneLocationsURL;
export const branded = brandedURL;
export const wishExpress = wishExpressURL;
export const yellowBadge = yellowBadgeURL;
export const cleanImage = cleanImageURL;
export const returnEnrolled = returnEnrolledURL;
export const clockCircleArrow = clockCircleArrowURL;
export const error403 = error403URL;
export const error404 = error404URL;
export const error500 = error500URL;
export const bannerUploadProducts = bannerUploadProductsURL;
export const bannerAddProductVariations = bannerAddProductVariationsURL;
export const ladyHoldingPackage = ladyHoldingPackageURL;
export const starFilled = starFilledURL;
export const starHalfFilled = starHalfFilledURL;
export const starUnfilled = starUnfilledURL;
export const announcementBadgeAdvancedLogisticsProgram =
  announcementBadgeAdvancedLogisticsProgramURL;
export const announcementBadgeEpc = announcementBadgeEpcURL;
export const announcementBadgeFbw = announcementBadgeFbwURL;
export const announcementBadgeMerchantFundedPromotions =
  announcementBadgeMerchantFundedPromotionsURL;
export const announcementBadgePlatinum = announcementBadgePlatinumURL;
export const announcementBadgeProductBoost = announcementBadgeProductBoostURL;
export const announcementBadgeRefunds = announcementBadgeRefundsURL;
export const announcementBadgeReturns = announcementBadgeReturnsURL;
export const announcementBadgeVideos = announcementBadgeVideosURL;
export const announcementBadgeWishExpressBlueBox =
  announcementBadgeWishExpressBlueBoxURL;
export const announcementBadgeWishPost = announcementBadgeWishPostURL;
export const announcementBadgeWishStandards = announcementBadgeWishStandardsURL;
export const homePbModalBudget = homePbModalBudgetURL;
export const homePbModalFbwDiscount = homePbModalFbwDiscountURL;
export const homePbModalLogo = homePbModalLogoURL;
export const homePbModalRefundAssurance = homePbModalRefundAssuranceURL;
export const homePbModalRocket = homePbModalRocketURL;
export const bannerBackToOnboarding = bannerBackToOnboardingURL;
export const bannerCustomerSupport = bannerCustomerSupportURL;
export const bannerMerchantBlog = bannerMerchantBlogURL;
export const bannerMfp = bannerMfpURL;
export const bannerOnboardingReview = bannerOnboardingReviewURL;
export const bannerProductBoostAutomatedCampaign =
  bannerProductBoostAutomatedCampaignURL;
export const bannerPbSeasonalBlackFriday = bannerPbSeasonalBlackFridayURL;
export const bannerPbSeasonalChineseNewYear = bannerPbSeasonalChineseNewYearURL;
export const bannerPbSeasonalCovid = bannerPbSeasonalCovidURL;
export const bannerPbSeasonalDefault = bannerPbSeasonalDefaultURL;
export const bannerPbSeasonalEaster = bannerPbSeasonalEasterURL;
export const bannerPbSeasonalHalloween = bannerPbSeasonalHalloweenURL;
export const bannerPbSeasonalIncreaseBudget = bannerPbSeasonalIncreaseBudgetURL;
export const bannerPbSeasonalJuly = bannerPbSeasonalJulyURL;
export const bannerPbSeasonalMayHighDemand = bannerPbSeasonalMayHighDemandURL;
export const bannerPbSeasonalMothersDay = bannerPbSeasonalMothersDayURL;
export const bannerPbSeasonalPreHoliday = bannerPbSeasonalPreHolidayURL;
export const bannerPbSeasonalSinglesDay = bannerPbSeasonalSinglesDayURL;
export const bannerPbSeasonalSummer = bannerPbSeasonalSummerURL;
export const bannerPbSeasonalThanksgiving = bannerPbSeasonalThanksgivingURL;
export const bannerSellerProfile = bannerSellerProfileURL;
export const bannerWeeklyDisbUpgrade = bannerWeeklyDisbUpgradeURL;
export const bannerWishClips = bannerWishClipsURL;
export const todoDeclineTaxSettings = todoDeclineTaxSettingsURL;
export const todoWishExpressWithText = todoWishExpressWithTextURL;
export const topSeller = topSellerURL;
export const wishExpressTruck = wishExpressTruckURL;
export const emptyImage = emptyImageURL;
export const authenticBrandSellerBadge = authenticBrandSellerBadgeURL;
export const mockMobileHeader = mockMobileHeaderURL;
export const homeFrsOptInModal = homeFrsOptInModalURL;
