import wishLogoInkURL from "public/images/wish-logo-ink.svg";
import wishLogoWhiteURL from "public/images/wish-logo-white.svg";
import merchantLogoWhiteCNURL from "public/images/merchant-logo/merchant-logo-white-cn.svg";
import merchantLogoCNURL from "public/images/merchant-logo/merchant-logo-cn.svg";
import merchantLogoWhiteCZURL from "public/images/merchant-logo/merchant-logo-white-cz.svg";
import merchantLogoCZURL from "public/images/merchant-logo/merchant-logo-cz.svg";
import merchantLogoWhiteDEURL from "public/images/merchant-logo/merchant-logo-white-de.svg";
import merchantLogoDEURL from "public/images/merchant-logo/merchant-logo-de.svg";
import merchantLogoWhiteESURL from "public/images/merchant-logo/merchant-logo-white-es.svg";
import merchantLogoESURL from "public/images/merchant-logo/merchant-logo-es.svg";
import merchantLogoWhiteFRURL from "public/images/merchant-logo/merchant-logo-white-fr.svg";
import merchantLogoFRURL from "public/images/merchant-logo/merchant-logo-fr.svg";
import merchantLogoWhiteITURL from "public/images/merchant-logo/merchant-logo-white-it.svg";
import merchantLogoITURL from "public/images/merchant-logo/merchant-logo-it.svg";
import merchantLogoWhiteJPURL from "public/images/merchant-logo/merchant-logo-white-jp.svg";
import merchantLogoJPURL from "public/images/merchant-logo/merchant-logo-jp.svg";
import merchantLogoWhiteKRURL from "public/images/merchant-logo/merchant-logo-white-kr.svg";
import merchantLogoKRURL from "public/images/merchant-logo/merchant-logo-kr.svg";
import merchantLogoWhiteNLURL from "public/images/merchant-logo/merchant-logo-white-nl.svg";
import merchantLogoNLURL from "public/images/merchant-logo/merchant-logo-nl.svg";
import merchantLogoWhitePTURL from "public/images/merchant-logo/merchant-logo-white-pt.svg";
import merchantLogoPTURL from "public/images/merchant-logo/merchant-logo-pt.svg";
import merchantLogoWhiteSEURL from "public/images/merchant-logo/merchant-logo-white-se.svg";
import merchantLogoSEURL from "public/images/merchant-logo/merchant-logo-se.svg";
import merchantLogoWhiteTRURL from "public/images/merchant-logo/merchant-logo-white-tr.svg";
import merchantLogoTRURL from "public/images/merchant-logo/merchant-logo-tr.svg";
import merchantLogoWhiteVNURL from "public/images/merchant-logo/merchant-logo-white-vn.svg";
import merchantLogoVNURL from "public/images/merchant-logo/merchant-logo-vn.svg";
import merchantLogoWhiteENURL from "public/images/merchant-logo/merchant-logo-white-en.svg";
import merchantLogoENURL from "public/images/merchant-logo/merchant-logo-en.svg";

import mmsWelcomeBusinessIntelligenceURL from "public/images/mms-welcome/mms-welcome-business-intelligence.svg";
import mmsWelcomeContentCreationURL from "public/images/mms-welcome/mms-welcome-content-creation.svg";
import mmsWelcomeCustomerServiceURL from "public/images/mms-welcome/mms-welcome-customer-service.svg";
import mmsWelcomeDesktopURL from "public/images/mms-welcome/mms-welcome-desktop.svg";
import mmsWelcomeInventoryManagementURL from "public/images/mms-welcome/mms-welcome-inventory-management.svg";
import mmsWelcomeLaptopSurveyURL from "public/images/mms-welcome/mms-welcome-laptop-survey.svg";
import mmsWelcomeListingURL from "public/images/mms-welcome/mms-welcome-listing.svg";
import mmsWelcomeLogisticsURL from "public/images/mms-welcome/mms-welcome-logistics.svg";
import mmsWelcomePencilURL from "public/images/mms-welcome/mms-welcome-pencil.svg";
import mmsWelcomePricingAdviceURL from "public/images/mms-welcome/mms-welcome-pricing-advice.svg";
import mmsWelcomeProductVerificationURL from "public/images/mms-welcome/mms-welcome-product-verification.svg";
import mmsWelcomeStoreSetupURL from "public/images/mms-welcome/mms-welcome-store-setup.svg";
import mmsWelcomeSuccessBannerURL from "public/images/mms-welcome/mms-welcome-success-banner.svg";
import mmsWelcomeTicketsCoinsURL from "public/images/mms-welcome/mms-welcome-tickets-coins.svg";
import mmsWelcomeTreeURL from "public/images/mms-welcome/mms-welcome-tree.svg";
import mmsWelcomeTruckURL from "public/images/mms-welcome/mms-welcome-truck.svg";
import mmsWelcomeUserTrafficURL from "public/images/mms-welcome/mms-welcome-user-traffic.svg";

import homeSelectedURL from "public/images/side-menu-icons/home-selected.svg";
import homeNotSelectedURL from "public/images/side-menu-icons/home-not-selected.svg";
import ordersSelectedURL from "public/images/side-menu-icons/orders-selected.svg";
import ordersNotSelectedURL from "public/images/side-menu-icons/orders-not-selected.svg";
import pbSelectedURL from "public/images/side-menu-icons/pb-selected.svg";
import pbNotSelectedURL from "public/images/side-menu-icons/pb-not-selected.svg";
import performanceSelectedURL from "public/images/side-menu-icons/performance-selected.svg";
import performanceNotSelectedURL from "public/images/side-menu-icons/performance-not-selected.svg";
import productsSelectedURL from "public/images/side-menu-icons/products-selected.svg";
import productsNotSelectedURL from "public/images/side-menu-icons/products-not-selected.svg";
import ticketsSelectedURL from "public/images/side-menu-icons/tickets-selected.svg";
import ticketsNotSelectedURL from "public/images/side-menu-icons/tickets-not-selected.svg";
import infractionsSelectedURL from "public/images/side-menu-icons/infractions-selected.svg";
import infractionsNotSelectedURL from "public/images/side-menu-icons/infractions-not-selected.svg";
import fbwFbsSelectedURL from "public/images/side-menu-icons/fbw-fbs-selected.svg";
import fbwFbsNotSelectedURL from "public/images/side-menu-icons/fbw-fbs-not-selected.svg";
import earlyPaymentSelectedURL from "public/images/side-menu-icons/early-payment-selected.svg";
import earlyPaymentNotSelectedURL from "public/images/side-menu-icons/early-payment-not-selected.svg";

import shippingPriceDropURL from "public/images/welcome-invite-only/shipping-price-drop.svg";
import manCheeringURL from "public/images/welcome-invite-only/man-cheering.svg";
import landingHeaderIllustrationLeftURL from "public/images/welcome-invite-only/landing-header-illustration-left.svg";
import landingHeaderIllustrationRightURL from "public/images/welcome-invite-only/landing-header-illustration-right.svg";
import landingHeaderIllustrationSmallerURL from "public/images/welcome-invite-only/landing-header-illustration-smaller.svg";
import globePhoneLocationsURL from "public/images/welcome-invite-only/globe-phone-locations.svg";

import error403URL from "public/images/error-403.svg";
import error404URL from "public/images/error-404.svg";
import error500URL from "public/images/error-500.svg";

export const wishLogoInk = wishLogoInkURL;
export const wishLogoWhite = wishLogoWhiteURL;
export const merchantLogoWhiteCN = merchantLogoWhiteCNURL;
export const merchantLogoCN = merchantLogoCNURL;
export const merchantLogoWhiteCZ = merchantLogoWhiteCZURL;
export const merchantLogoCZ = merchantLogoCZURL;
export const merchantLogoWhiteDE = merchantLogoWhiteDEURL;
export const merchantLogoDE = merchantLogoDEURL;
export const merchantLogoWhiteES = merchantLogoWhiteESURL;
export const merchantLogoES = merchantLogoESURL;
export const merchantLogoWhiteFR = merchantLogoWhiteFRURL;
export const merchantLogoFR = merchantLogoFRURL;
export const merchantLogoWhiteIT = merchantLogoWhiteITURL;
export const merchantLogoIT = merchantLogoITURL;
export const merchantLogoWhiteJP = merchantLogoWhiteJPURL;
export const merchantLogoJP = merchantLogoJPURL;
export const merchantLogoWhiteKR = merchantLogoWhiteKRURL;
export const merchantLogoKR = merchantLogoKRURL;
export const merchantLogoWhiteNL = merchantLogoWhiteNLURL;
export const merchantLogoNL = merchantLogoNLURL;
export const merchantLogoWhitePT = merchantLogoWhitePTURL;
export const merchantLogoPT = merchantLogoPTURL;
export const merchantLogoWhiteSE = merchantLogoWhiteSEURL;
export const merchantLogoSE = merchantLogoSEURL;
export const merchantLogoWhiteTR = merchantLogoWhiteTRURL;
export const merchantLogoTR = merchantLogoTRURL;
export const merchantLogoWhiteVN = merchantLogoWhiteVNURL;
export const merchantLogoVN = merchantLogoVNURL;
export const merchantLogoWhiteEN = merchantLogoWhiteENURL;
export const merchantLogoEN = merchantLogoENURL;
export const mmsWelcomeBusinessIntelligence = mmsWelcomeBusinessIntelligenceURL;
export const mmsWelcomeContentCreation = mmsWelcomeContentCreationURL;
export const mmsWelcomeCustomerService = mmsWelcomeCustomerServiceURL;
export const mmsWelcomeDesktop = mmsWelcomeDesktopURL;
export const mmsWelcomeInventoryManagement = mmsWelcomeInventoryManagementURL;
export const mmsWelcomeLaptopSurvey = mmsWelcomeLaptopSurveyURL;
export const mmsWelcomeListing = mmsWelcomeListingURL;
export const mmsWelcomeLogistics = mmsWelcomeLogisticsURL;
export const mmsWelcomePencil = mmsWelcomePencilURL;
export const mmsWelcomePricingAdvice = mmsWelcomePricingAdviceURL;
export const mmsWelcomeProductVerification = mmsWelcomeProductVerificationURL;
export const mmsWelcomeStoreSetup = mmsWelcomeStoreSetupURL;
export const mmsWelcomeSuccessBanner = mmsWelcomeSuccessBannerURL;
export const mmsWelcomeTicketsCoins = mmsWelcomeTicketsCoinsURL;
export const mmsWelcomeTree = mmsWelcomeTreeURL;
export const mmsWelcomeTruck = mmsWelcomeTruckURL;
export const mmsWelcomeUserTraffic = mmsWelcomeUserTrafficURL;
export const homeSelected = homeSelectedURL;
export const homeNotSelected = homeNotSelectedURL;
export const ordersSelected = ordersSelectedURL;
export const ordersNotSelected = ordersNotSelectedURL;
export const pbSelected = pbSelectedURL;
export const pbNotSelected = pbNotSelectedURL;
export const performanceSelected = performanceSelectedURL;
export const performanceNotSelected = performanceNotSelectedURL;
export const productsSelected = productsSelectedURL;
export const productsNotSelected = productsNotSelectedURL;
export const ticketsSelected = ticketsSelectedURL;
export const ticketsNotSelected = ticketsNotSelectedURL;
export const infractionsSelected = infractionsSelectedURL;
export const infractionsNotSelected = infractionsNotSelectedURL;
export const fbwFbsSelected = fbwFbsSelectedURL;
export const fbwFbsNotSelected = fbwFbsNotSelectedURL;
export const earlyPaymentSelected = earlyPaymentSelectedURL;
export const earlyPaymentNotSelected = earlyPaymentNotSelectedURL;
export const shippingPriceDrop = shippingPriceDropURL;
export const manCheering = manCheeringURL;
export const landingHeaderIllustrationLeft = landingHeaderIllustrationLeftURL;
export const landingHeaderIllustrationRight = landingHeaderIllustrationRightURL;
export const landingHeaderIllustrationSmaller =
  landingHeaderIllustrationSmallerURL;
export const globePhoneLocations = globePhoneLocationsURL;
export const error403 = error403URL;
export const error404 = error404URL;
export const error500 = error500URL;
