import wishLogoInkUrl from "public/images/wish-logo-ink.svg";
import wishLogoWhiteUrl from "public/images/wish-logo-white.svg";
import merchantLogoWhiteCNUrl from "public/images/merchant-logo/merchant-logo-white-cn.svg";
import merchantLogoCNUrl from "public/images/merchant-logo/merchant-logo-cn.svg";
import merchantLogoWhiteCZUrl from "public/images/merchant-logo/merchant-logo-white-cz.svg";
import merchantLogoCZUrl from "public/images/merchant-logo/merchant-logo-cz.svg";
import merchantLogoWhiteDEUrl from "public/images/merchant-logo/merchant-logo-white-de.svg";
import merchantLogoDEUrl from "public/images/merchant-logo/merchant-logo-de.svg";
import merchantLogoWhiteESUrl from "public/images/merchant-logo/merchant-logo-white-es.svg";
import merchantLogoESUrl from "public/images/merchant-logo/merchant-logo-es.svg";
import merchantLogoWhiteFRUrl from "public/images/merchant-logo/merchant-logo-white-fr.svg";
import merchantLogoFRUrl from "public/images/merchant-logo/merchant-logo-fr.svg";
import merchantLogoWhiteITUrl from "public/images/merchant-logo/merchant-logo-white-it.svg";
import merchantLogoITUrl from "public/images/merchant-logo/merchant-logo-it.svg";
import merchantLogoWhiteJPUrl from "public/images/merchant-logo/merchant-logo-white-jp.svg";
import merchantLogoJPUrl from "public/images/merchant-logo/merchant-logo-jp.svg";
import merchantLogoWhiteKRUrl from "public/images/merchant-logo/merchant-logo-white-kr.svg";
import merchantLogoKRUrl from "public/images/merchant-logo/merchant-logo-kr.svg";
import merchantLogoWhiteNLUrl from "public/images/merchant-logo/merchant-logo-white-nl.svg";
import merchantLogoNLUrl from "public/images/merchant-logo/merchant-logo-nl.svg";
import merchantLogoWhitePTUrl from "public/images/merchant-logo/merchant-logo-white-pt.svg";
import merchantLogoPTUrl from "public/images/merchant-logo/merchant-logo-pt.svg";
import merchantLogoWhiteSEUrl from "public/images/merchant-logo/merchant-logo-white-se.svg";
import merchantLogoSEUrl from "public/images/merchant-logo/merchant-logo-se.svg";
import merchantLogoWhiteTRUrl from "public/images/merchant-logo/merchant-logo-white-tr.svg";
import merchantLogoTRUrl from "public/images/merchant-logo/merchant-logo-tr.svg";
import merchantLogoWhiteVNUrl from "public/images/merchant-logo/merchant-logo-white-vn.svg";
import merchantLogoVNUrl from "public/images/merchant-logo/merchant-logo-vn.svg";
import merchantLogoWhiteENUrl from "public/images/merchant-logo/merchant-logo-white-en.svg";
import merchantLogoENUrl from "public/images/merchant-logo/merchant-logo-en.svg";

import mmsWelcomeBusinessIntelligenceUrl from "public/images/mms-welcome/mms-welcome-business-intelligence.svg";
import mmsWelcomeContentCreationUrl from "public/images/mms-welcome/mms-welcome-content-creation.svg";
import mmsWelcomeCustomerServiceUrl from "public/images/mms-welcome/mms-welcome-customer-service.svg";
import mmsWelcomeDesktopUrl from "public/images/mms-welcome/mms-welcome-desktop.svg";
import mmsWelcomeInventoryManagementUrl from "public/images/mms-welcome/mms-welcome-inventory-management.svg";
import mmsWelcomeLaptopSurveyUrl from "public/images/mms-welcome/mms-welcome-laptop-survey.svg";
import mmsWelcomeListingUrl from "public/images/mms-welcome/mms-welcome-listing.svg";
import mmsWelcomeLogisticsUrl from "public/images/mms-welcome/mms-welcome-logistics.svg";
import mmsWelcomePencilUrl from "public/images/mms-welcome/mms-welcome-pencil.svg";
import mmsWelcomePricingAdviceUrl from "public/images/mms-welcome/mms-welcome-pricing-advice.svg";
import mmsWelcomeProductVerificationUrl from "public/images/mms-welcome/mms-welcome-product-verification.svg";
import mmsWelcomeStoreSetupUrl from "public/images/mms-welcome/mms-welcome-store-setup.svg";
import mmsWelcomeSuccessBannerUrl from "public/images/mms-welcome/mms-welcome-success-banner.svg";
import mmsWelcomeTicketsCoinsUrl from "public/images/mms-welcome/mms-welcome-tickets-coins.svg";
import mmsWelcomeTreeUrl from "public/images/mms-welcome/mms-welcome-tree.svg";
import mmsWelcomeTruckUrl from "public/images/mms-welcome/mms-welcome-truck.svg";
import mmsWelcomeUserTrafficUrl from "public/images/mms-welcome/mms-welcome-user-traffic.svg";

import homeSelectedUrl from "public/images/side-menu-icons/home-selected.svg";
import homeNotSelectedUrl from "public/images/side-menu-icons/home-not-selected.svg";
import ordersSelectedUrl from "public/images/side-menu-icons/orders-selected.svg";
import ordersNotSelectedUrl from "public/images/side-menu-icons/orders-not-selected.svg";
import pbSelectedUrl from "public/images/side-menu-icons/pb-selected.svg";
import pbNotSelectedUrl from "public/images/side-menu-icons/pb-not-selected.svg";
import performanceSelectedUrl from "public/images/side-menu-icons/performance-selected.svg";
import performanceNotSelectedUrl from "public/images/side-menu-icons/performance-not-selected.svg";
import productsSelectedUrl from "public/images/side-menu-icons/products-selected.svg";
import productsNotSelectedUrl from "public/images/side-menu-icons/products-not-selected.svg";
import ticketsSelectedUrl from "public/images/side-menu-icons/tickets-selected.svg";
import ticketsNotSelectedUrl from "public/images/side-menu-icons/tickets-not-selected.svg";
import infractionsSelectedUrl from "public/images/side-menu-icons/infractions-selected.svg";
import infractionsNotSelectedUrl from "public/images/side-menu-icons/infractions-not-selected.svg";
import fbwFbsSelectedUrl from "public/images/side-menu-icons/fbw-fbs-selected.svg";
import fbwFbsNotSelectedUrl from "public/images/side-menu-icons/fbw-fbs-not-selected.svg";
import earlyPaymentSelectedUrl from "public/images/side-menu-icons/early-payment-selected.svg";
import earlyPaymentNotSelectedUrl from "public/images/side-menu-icons/early-payment-not-selected.svg";

import shippingPriceDropUrl from "public/images/welcome-invite-only/shipping-price-drop.svg";
import manCheeringUrl from "public/images/welcome-invite-only/man-cheering.svg";
import landingHeaderIllustrationLeftUrl from "public/images/welcome-invite-only/landing-header-illustration-left.svg";
import landingHeaderIllustrationRightUrl from "public/images/welcome-invite-only/landing-header-illustration-right.svg";
import landingHeaderIllustrationSmallerUrl from "public/images/welcome-invite-only/landing-header-illustration-smaller.svg";
import globePhoneLocationsUrl from "public/images/welcome-invite-only/globe-phone-locations.svg";

import brandedUrl from "public/images/product-badges/branded.svg";
import wishExpressUrl from "public/images/product-badges/wish-express.svg";
import yellowBadgeUrl from "public/images/product-badges/yellow-badge.svg";
import cleanImageUrl from "public/images/product-badges/clean-image.svg";
import returnEnrolledUrl from "public/images/product-badges/return-enrolled.svg";
import clockCircleArrowUrl from "public/images/clock-circle-arrow.svg";

import error403Url from "public/images/error-403.svg";
import error404Url from "public/images/error-404.svg";
import error500Url from "public/images/error-500.svg";

import bannerUploadProductsUrl from "public/images/home/banner-upload-products.svg";
import bannerAddProductVariationsUrl from "public/images/home/banner-add-product-variations.svg";
import ladyHoldingPackageUrl from "public/images/home/lady-holding-package.svg";
import starFilledUrl from "public/images/home/star-filled.svg";
import starHalfFilledUrl from "public/images/home/star-half-filled.svg";
import starUnfilledUrl from "public/images/home/star-unfilled.svg";
import announcementBadgeAdvancedLogisticsProgramUrl from "public/images/home/announcement-icons/advanced-logistics-program.svg";
import announcementBadgeEpcUrl from "public/images/home/announcement-icons/epc.svg";
import announcementBadgeFbwUrl from "public/images/home/announcement-icons/fbw.svg";
import announcementBadgeMerchantFundedPromotionsUrl from "public/images/home/announcement-icons/merchant-funded-promotions.svg";
import announcementBadgePlatinumUrl from "public/images/home/announcement-icons/platinum.svg";
import announcementBadgeProductBoostUrl from "public/images/home/announcement-icons/product-boost.svg";
import announcementBadgeRefundsUrl from "public/images/home/announcement-icons/refunds.svg";
import announcementBadgeReturnsUrl from "public/images/home/announcement-icons/returns.svg";
import announcementBadgeVideosUrl from "public/images/home/announcement-icons/videos.svg";
import announcementBadgeWishExpressBlueBoxUrl from "public/images/home/announcement-icons/wish-express-blue-box.svg";
import announcementBadgeWishPostUrl from "public/images/home/announcement-icons/wish-post.svg";
import announcementBadgeWishStandardsUrl from "public/images/home/announcement-icons/wish-standards.svg";
import homePbModalBudgetUrl from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-budget.svg";
import homePbModalFbwDiscountUrl from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-fbw-discount.svg";
import homePbModalLogoUrl from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-logo.svg";
import homePbModalRefundAssuranceUrl from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-refund-assurance.svg";
import homePbModalRocketUrl from "public/images/home/announcement-modal/product-boost-announcement/home-pb-modal-rocket.png";
import homeFrsOptInModalUrl from "public/images/home/announcement-modal/home-frs-opt-in-modal.svg";

import bannerBackToOnboardingUrl from "public/images/home/banner-images/banner-back-to-onboarding.svg";
import bannerCustomerSupportUrl from "public/images/home/banner-images/banner-customer-support.svg";
import bannerMerchantBlogUrl from "public/images/home/banner-images/banner-merchant-blog.svg";
import bannerMfpUrl from "public/images/home/banner-images/banner-mfp.svg";
import bannerOnboardingReviewUrl from "public/images/home/banner-images/banner-onboarding-review.svg";
import bannerProductBoostAutomatedCampaignUrl from "public/images/home/banner-images/banner-product-boost-automated-campaign.svg";
import bannerPbSeasonalBlackFridayUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-black-friday.png";
import bannerPbSeasonalChineseNewYearUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-chinese-new-year.svg";
import bannerPbSeasonalCovidUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-covid.svg";
import bannerPbSeasonalDefaultUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-default.svg";
import bannerPbSeasonalEasterUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-easter.svg";
import bannerPbSeasonalHalloweenUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-halloween.svg";
import bannerPbSeasonalIncreaseBudgetUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-increase-budget.svg";
import bannerPbSeasonalJulyUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-july.svg";
import bannerPbSeasonalMayHighDemandUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-may-high-demand.svg";
import bannerPbSeasonalMothersDayUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-mothers-day.svg";
import bannerPbSeasonalPreHolidayUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-pre-holiday.svg";
import bannerPbSeasonalSinglesDayUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-singles-day.svg";
import bannerPbSeasonalSummerUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-summer.svg";
import bannerPbSeasonalThanksgivingUrl from "public/images/home/banner-images/pb-seasonal/banner-pb-seasonal-thanksgiving.svg";
import bannerSellerProfileUrl from "public/images/home/banner-images/banner-seller-profile.svg";
import bannerWeeklyDisbUpgradeUrl from "public/images/home/banner-images/banner-weekly-disb-upgrade.svg";
import bannerWishClipsUrl from "public/images/home/banner-images/banner-wish-clips.png";
import bannerMerchantSummitUrl from "public/images/home/banner-images/banner-merchant-summit.png";
import bannerEUMerchantSummitUrl from "public/images/home/banner-images/banner-eu-merchant-summit.png";

import todoDeclineTaxSettingsUrl from "public/images/home/todo/todo-decline-tax-settings.svg";
import todoWishExpressWithTextUrl from "public/images/home/todo/todo-wish-express-with-text.svg";

import topSellerUrl from "public/images/top-seller.svg";
import wishExpressTruckUrl from "public/images/wish-express.svg";
import emptyImageUrl from "public/images/emptyimage.svg";
import authenticBrandSellerBadgeUrl from "public/images/authentic_brand_seller_badge.svg";
import mockMobileHeaderUrl from "public/images/mock-mobile-header.png";
import magnifierUrl from "public/images/product-csv/magnifier.svg";

import wssPlatinumBadgeUrl from "public/images/wss/platinum-badge.svg";
import wssGoldBadgeUrl from "public/images/wss/gold-badge.svg";
import wssSilverBadgeUrl from "public/images/wss/silver-badge.svg";
import wssBronzeBadgeUrl from "public/images/wss/bronze-badge.svg";
import wssUnratedBadgeUrl from "public/images/wss/unrated-badge.svg";
import wssBannedBadgeUrl from "public/images/warning-filled.svg";
import warningFilledUrl from "public/images/warning-filled.svg";
import darkGreenCheckmarkFilledUrl from "public/images/dark-green-checkmark-filled.svg";
import oneExclamationUrl from "public/images/one-exclamation.svg";
import twoExclamationUrl from "public/images/two-exclamation.svg";
import wssDeepDiveNoTableDataUrl from "public/images/wss-deep-dive-no-table-data.svg";
import productsParcelUrl from "public/images/products-parcel.svg";

export const wishLogoInk = wishLogoInkUrl;
export const wishLogoWhite = wishLogoWhiteUrl;
export const merchantLogoWhiteCN = merchantLogoWhiteCNUrl;
export const merchantLogoCN = merchantLogoCNUrl;
export const merchantLogoWhiteCZ = merchantLogoWhiteCZUrl;
export const merchantLogoCZ = merchantLogoCZUrl;
export const merchantLogoWhiteDE = merchantLogoWhiteDEUrl;
export const merchantLogoDE = merchantLogoDEUrl;
export const merchantLogoWhiteES = merchantLogoWhiteESUrl;
export const merchantLogoES = merchantLogoESUrl;
export const merchantLogoWhiteFR = merchantLogoWhiteFRUrl;
export const merchantLogoFR = merchantLogoFRUrl;
export const merchantLogoWhiteIT = merchantLogoWhiteITUrl;
export const merchantLogoIT = merchantLogoITUrl;
export const merchantLogoWhiteJP = merchantLogoWhiteJPUrl;
export const merchantLogoJP = merchantLogoJPUrl;
export const merchantLogoWhiteKR = merchantLogoWhiteKRUrl;
export const merchantLogoKR = merchantLogoKRUrl;
export const merchantLogoWhiteNL = merchantLogoWhiteNLUrl;
export const merchantLogoNL = merchantLogoNLUrl;
export const merchantLogoWhitePT = merchantLogoWhitePTUrl;
export const merchantLogoPT = merchantLogoPTUrl;
export const merchantLogoWhiteSE = merchantLogoWhiteSEUrl;
export const merchantLogoSE = merchantLogoSEUrl;
export const merchantLogoWhiteTR = merchantLogoWhiteTRUrl;
export const merchantLogoTR = merchantLogoTRUrl;
export const merchantLogoWhiteVN = merchantLogoWhiteVNUrl;
export const merchantLogoVN = merchantLogoVNUrl;
export const merchantLogoWhiteEN = merchantLogoWhiteENUrl;
export const merchantLogoEN = merchantLogoENUrl;
export const mmsWelcomeBusinessIntelligence = mmsWelcomeBusinessIntelligenceUrl;
export const mmsWelcomeContentCreation = mmsWelcomeContentCreationUrl;
export const mmsWelcomeCustomerService = mmsWelcomeCustomerServiceUrl;
export const mmsWelcomeDesktop = mmsWelcomeDesktopUrl;
export const mmsWelcomeInventoryManagement = mmsWelcomeInventoryManagementUrl;
export const mmsWelcomeLaptopSurvey = mmsWelcomeLaptopSurveyUrl;
export const mmsWelcomeListing = mmsWelcomeListingUrl;
export const mmsWelcomeLogistics = mmsWelcomeLogisticsUrl;
export const mmsWelcomePencil = mmsWelcomePencilUrl;
export const mmsWelcomePricingAdvice = mmsWelcomePricingAdviceUrl;
export const mmsWelcomeProductVerification = mmsWelcomeProductVerificationUrl;
export const mmsWelcomeStoreSetup = mmsWelcomeStoreSetupUrl;
export const mmsWelcomeSuccessBanner = mmsWelcomeSuccessBannerUrl;
export const mmsWelcomeTicketsCoins = mmsWelcomeTicketsCoinsUrl;
export const mmsWelcomeTree = mmsWelcomeTreeUrl;
export const mmsWelcomeTruck = mmsWelcomeTruckUrl;
export const mmsWelcomeUserTraffic = mmsWelcomeUserTrafficUrl;
export const homeSelected = homeSelectedUrl;
export const homeNotSelected = homeNotSelectedUrl;
export const ordersSelected = ordersSelectedUrl;
export const ordersNotSelected = ordersNotSelectedUrl;
export const pbSelected = pbSelectedUrl;
export const pbNotSelected = pbNotSelectedUrl;
export const performanceSelected = performanceSelectedUrl;
export const performanceNotSelected = performanceNotSelectedUrl;
export const productsSelected = productsSelectedUrl;
export const productsNotSelected = productsNotSelectedUrl;
export const ticketsSelected = ticketsSelectedUrl;
export const ticketsNotSelected = ticketsNotSelectedUrl;
export const infractionsSelected = infractionsSelectedUrl;
export const infractionsNotSelected = infractionsNotSelectedUrl;
export const fbwFbsSelected = fbwFbsSelectedUrl;
export const fbwFbsNotSelected = fbwFbsNotSelectedUrl;
export const earlyPaymentSelected = earlyPaymentSelectedUrl;
export const earlyPaymentNotSelected = earlyPaymentNotSelectedUrl;
export const shippingPriceDrop = shippingPriceDropUrl;
export const manCheering = manCheeringUrl;
export const landingHeaderIllustrationLeft = landingHeaderIllustrationLeftUrl;
export const landingHeaderIllustrationRight = landingHeaderIllustrationRightUrl;
export const landingHeaderIllustrationSmaller =
  landingHeaderIllustrationSmallerUrl;
export const globePhoneLocations = globePhoneLocationsUrl;
export const branded = brandedUrl;
export const wishExpress = wishExpressUrl;
export const yellowBadge = yellowBadgeUrl;
export const cleanImage = cleanImageUrl;
export const returnEnrolled = returnEnrolledUrl;
export const clockCircleArrow = clockCircleArrowUrl;
export const error403 = error403Url;
export const error404 = error404Url;
export const error500 = error500Url;
export const bannerUploadProducts = bannerUploadProductsUrl;
export const bannerAddProductVariations = bannerAddProductVariationsUrl;
export const ladyHoldingPackage = ladyHoldingPackageUrl;
export const starFilled = starFilledUrl;
export const starHalfFilled = starHalfFilledUrl;
export const starUnfilled = starUnfilledUrl;
export const announcementBadgeAdvancedLogisticsProgram =
  announcementBadgeAdvancedLogisticsProgramUrl;
export const announcementBadgeEpc = announcementBadgeEpcUrl;
export const announcementBadgeFbw = announcementBadgeFbwUrl;
export const announcementBadgeMerchantFundedPromotions =
  announcementBadgeMerchantFundedPromotionsUrl;
export const announcementBadgePlatinum = announcementBadgePlatinumUrl;
export const announcementBadgeProductBoost = announcementBadgeProductBoostUrl;
export const announcementBadgeRefunds = announcementBadgeRefundsUrl;
export const announcementBadgeReturns = announcementBadgeReturnsUrl;
export const announcementBadgeVideos = announcementBadgeVideosUrl;
export const announcementBadgeWishExpressBlueBox =
  announcementBadgeWishExpressBlueBoxUrl;
export const announcementBadgeWishPost = announcementBadgeWishPostUrl;
export const announcementBadgeWishStandards = announcementBadgeWishStandardsUrl;
export const homePbModalBudget = homePbModalBudgetUrl;
export const homePbModalFbwDiscount = homePbModalFbwDiscountUrl;
export const homePbModalLogo = homePbModalLogoUrl;
export const homePbModalRefundAssurance = homePbModalRefundAssuranceUrl;
export const homePbModalRocket = homePbModalRocketUrl;
export const bannerBackToOnboarding = bannerBackToOnboardingUrl;
export const bannerCustomerSupport = bannerCustomerSupportUrl;
export const bannerMerchantBlog = bannerMerchantBlogUrl;
export const bannerMfp = bannerMfpUrl;
export const bannerOnboardingReview = bannerOnboardingReviewUrl;
export const bannerProductBoostAutomatedCampaign =
  bannerProductBoostAutomatedCampaignUrl;
export const bannerPbSeasonalBlackFriday = bannerPbSeasonalBlackFridayUrl;
export const bannerPbSeasonalChineseNewYear = bannerPbSeasonalChineseNewYearUrl;
export const bannerPbSeasonalCovid = bannerPbSeasonalCovidUrl;
export const bannerPbSeasonalDefault = bannerPbSeasonalDefaultUrl;
export const bannerPbSeasonalEaster = bannerPbSeasonalEasterUrl;
export const bannerPbSeasonalHalloween = bannerPbSeasonalHalloweenUrl;
export const bannerPbSeasonalIncreaseBudget = bannerPbSeasonalIncreaseBudgetUrl;
export const bannerPbSeasonalJuly = bannerPbSeasonalJulyUrl;
export const bannerPbSeasonalMayHighDemand = bannerPbSeasonalMayHighDemandUrl;
export const bannerPbSeasonalMothersDay = bannerPbSeasonalMothersDayUrl;
export const bannerPbSeasonalPreHoliday = bannerPbSeasonalPreHolidayUrl;
export const bannerPbSeasonalSinglesDay = bannerPbSeasonalSinglesDayUrl;
export const bannerPbSeasonalSummer = bannerPbSeasonalSummerUrl;
export const bannerPbSeasonalThanksgiving = bannerPbSeasonalThanksgivingUrl;
export const bannerSellerProfile = bannerSellerProfileUrl;
export const bannerWeeklyDisbUpgrade = bannerWeeklyDisbUpgradeUrl;
export const bannerWishClips = bannerWishClipsUrl;
export const bannerMerchantSummit = bannerMerchantSummitUrl;
export const bannerEUMerchantSummit = bannerEUMerchantSummitUrl;
export const todoDeclineTaxSettings = todoDeclineTaxSettingsUrl;
export const todoWishExpressWithText = todoWishExpressWithTextUrl;
export const topSeller = topSellerUrl;
export const wishExpressTruck = wishExpressTruckUrl;
export const emptyImage = emptyImageUrl;
export const authenticBrandSellerBadge = authenticBrandSellerBadgeUrl;
export const mockMobileHeader = mockMobileHeaderUrl;
export const homeFrsOptInModal = homeFrsOptInModalUrl;
export const magnifier = magnifierUrl;
export const wssPlatinumBadge = wssPlatinumBadgeUrl;
export const wssGoldBadge = wssGoldBadgeUrl;
export const wssSilverBadge = wssSilverBadgeUrl;
export const wssBronzeBadge = wssBronzeBadgeUrl;
export const wssUnratedBadge = wssUnratedBadgeUrl;
export const wssBannedBadge = wssBannedBadgeUrl;
export const warningFilled = warningFilledUrl;
export const darkGreenCheckmarkFilled = darkGreenCheckmarkFilledUrl;
export const oneExclamation = oneExclamationUrl;
export const twoExclamation = twoExclamationUrl;
export const wssDeepDiveNoTableData = wssDeepDiveNoTableDataUrl;
export const productsParcel = productsParcelUrl;
