export const PRODUCT_COMPLIANCE_THRESHOLD = 0;
export const SHIPPING_LATE_CONFIRM_THRESHOLD = 0.01;
export const SHIPPING_VALID_TRACKING_THRESHOLD = 0.99;
export const CS_LATE_RESPONSE_THRESHOLD = 0.15;
export const CS_SATISFACTION_THRESHOLD = 0.8;
export const RATING_THRESHOLD = 3;

export enum Page {
  performanceOverview = "PERFORMANCE_OVERVIEW",
  salesMetrics = "SALES_METRICS",
  storeHealth = "STORE_HEALTH",
}

export const LogActions = {
  LAND_FROM_ENTRY: "LAND_FROM_ENTRY",
  CLICK: "CLICK",
  CLICK_DROPDOWN: "CLICK_DROPDOWN",
  SEARCH: "SEARCH",
  EXPAND: "EXPAND",
  ACTION_CLICK: "ACTION_CLICK",
};

export const LogEventNames = {
  LANDING: "LANDING",

  // Sales metrics
  SALES_CHANGE_TIME_FRAME: "SALES_CHANGE_TIME_FRAME",
  VIEW_SALES_PERFORMANCE: "VIEW_SALES_PERFORMANCE",
  PRODUCTS_CHANGE_TIME_FRAME: "PRODUCTS_CHANGE_TIME_FRAME",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  EXPAND_PRODUCTS_SALES_GRAPH: "EXPAND_PRODUCTS_SALES_GRAPH",
  EDIT_PRODUCT_LISTING: "EDIT_PRODUCT_LISTING",
  CREATE_PB_CAMPAIGN: "CREATE_PB_CAMPAIGN",
  CREATE_PD_CAMPAIGN: "CREATE_PD_CAMPAIGN",
  NEXT_X_PRODUCTS: "NEXT_X_PRODUCTS",
  CHANGE_PRODUCTS_DISPLAY_NUMBER: "CHANGE_PRODUCTS_DISPLAY_NUMBER",

  // Store health
  CLICK_TO_STORE_HEALTH: "CLICK_TO_STORE_HEALTH",
  VIEW_SHIPPING_PERFORMANCE: "CLICK_VIEW_SHIPPING_PERFORMANCE",
  RESOLVE_INFRACTIONS: "RESOLVE_INFRACTIONS",
  VIEW_REFUND_PERFORMANCE: "VIEW_REFUND_PERFORMANCE",
  VIEW_RATING_PERFORMANCE: "VIEW_RATING_PERFORMANCE",
  VIEW_CS_PERFORMANCE: "VIEW_CS_PERFORMANCE",
  SHIPPING_LEARN_MORE: "SHIPPING_LEARN_MORE",
  PRODUCT_COMPLIANCE_LEARN_MORE: "PRODUCT_COMPLIANCE_LEARN_MORE",
  REFUNDS_LEARN_MORE: "REFUNDS_LEARN_MORE",
  RATINGS_LEARN_MORE: "RATINGS_LEARN_MORE",
  CS_LEARN_MORE: "CS_LEARN_MORE",
  SHIPPING_POLICY: "SHIPPING_POLICY",
  VALID_TRACKING_REFUND_POLICY: "VALID_TRACKING_REFUND_POLICY",
  INTELLECTUAL_PROPERTY_POLICY: "INTELLECTUAL_PROPERTY_POLICY",
  PROHIBITED_PRODUCTS_POLICY: "PROHIBITED_PRODUCTS_POLICY",
  MISLEADING_PRODUCTS_POLICY: "MISLEADING_PRODUCTS_POLICY",
  HIGH_REFUND_RATE_SUSPENSION_POLICY: "HIGH_REFUND_RATE_SUSPENSION_POLICY",
  HIGH_REFUND_RATE_PAYMENT_POLICY: "HIGH_REFUND_RATE_PAYMENT_POLICY",
};
