import React, { useMemo } from "react";
import Head from "next/head";
import Image from "next/image";
import { StyleSheet } from "aphrodite";
import { css } from "@toolkit/styling";

// Rehydrate to ensure that the client doesn't duplicate styles
// It has to execute before any code that defines styles
// '__REHYDRATE_IDS' is set in '_document.js'
if (typeof window !== "undefined") {
  // @ts-ignore: aphrodite SSR is not compatible with TS [lliepert]
  StyleSheet.rehydrate(window.__REHYDRATE_IDS);
}

const Home: React.FC = () => {
  const styles = useStylesheet();

  return (
    <div className={css(styles.container)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css(styles.main)}>
        <h1 className={css(styles.title)}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={css(styles.description)}>
          Get started by editing{" "}
          <code className={css(styles.code)}>pages/index.js</code>
        </p>

        <div className={css(styles.grid)}>
          <a href="https://nextjs.org/docs" className={css(styles.card)}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={css(styles.card)}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={css(styles.card)}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={css(styles.card)}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={css(styles.footer)}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={css(styles.logo)}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

const useStylesheet = () =>
  useMemo(
    () =>
      StyleSheet.create({
        container: {
          minHeight: "100vh",
          padding: "0 0.5rem",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
        },
        main: {
          padding: "5rem 0",
          flex: 1,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        },
        footer: {
          width: "100%",
          height: "100px",
          borderTop: "1px solid #eaeaea",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          ":nth-child(1n) > a": {
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            flexGrow: 1,
          },
        },
        title: {
          margin: "0",
          lineHeight: 1.15,
          fontSize: "4rem",
          textAlign: "center",
          ":nth-child(1n) > a": {
            color: "#0070f3",
            textDecoration: "none",
            ":hover": {
              textDecoration: "underline",
            },
            ":focus": {
              textDecoration: "underline",
            },
            ":active": {
              textDecoration: "underline",
            },
          },
        },
        description: {
          textAlign: "center",
          lineHeight: 1.5,
          fontSize: "1.5rem",
        },
        code: {
          background: "#fafafa",
          borderRadius: "5px",
          padding: "0.75rem",
          fontSize: "1.1rem",
          fontFamily:
            "Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,\n    Bitstream Vera Sans Mono, Courier New, monospace",
        },
        grid: {
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexWrap: "wrap",
          maxWidth: "800px",
          marginTop: "3rem",
        },
        card: {
          margin: "1rem",
          padding: "1.5rem",
          textAlign: "left",
          color: "inherit",
          textDecoration: "none",
          border: "1px solid #eaeaea",
          borderRadius: "10px",
          transition: "color 0.15s ease, border-color 0.15s ease",
          width: "45%",
          ":hover": {
            color: "#0070f3",
            borderColor: "#0070f3",
          },
          ":focus": {
            color: "#0070f3",
            borderColor: "#0070f3",
          },
          ":active": {
            color: "#0070f3",
            borderColor: "#0070f3",
          },
          ":nth-child(1n) > h2": {
            margin: "0 0 1rem 0",
            fontSize: "1.5rem",
          },
          ":nth-child(1n) > p": {
            margin: "0",
            fontSize: "1.25rem",
            lineHeight: 1.5,
          },
        },
        logo: { height: "1em", marginLeft: "0.5rem" },
        "@media (max-width: 600px)": {
          grid: { width: "100%", flexDirection: "column" },
        },
      }),
    [],
  );
