import React, { useMemo } from "react";
import { StyleSheet } from "aphrodite";
import { observer } from "mobx-react";

/* Lego Components */
import { Link } from "@ContextLogic/lego";

/* Lego Toolkit */
import { css } from "@toolkit/styling";
import { formatCurrency } from "@ContextLogic/lego/toolkit/currency";
import { zendeskURL } from "@toolkit/url";

import { PolicyProps } from "@merchant/component/policy/policies/PolicySection";
import PolicySubSection from "@merchant/component/policy/policies/PolicySubSection";

const Section12 = ({
  className,
  sectionNumber,
  currentSection,
}: PolicyProps) => {
  const styles = useStylesheet();

  return (
    <PolicySubSection
      title={i`Manipulated Reviews and Ratings Policy`}
      subSectionNumber={`${sectionNumber}.12`}
      currentSection={currentSection}
    >
      <p>
        Wish strictly prohibits any attempt to manipulate customer reviews
        and/or ratings, and expressly prohibits compensated reviews and/or
        ratings. Any reviews and/or ratings generated by the merchants directly
        or indirectly are also prohibited. Orders that are found to have been
        affected by manipulated reviews and/or ratings are subject to be
        penalized the order value plus {formatCurrency(100, "USD")}* per
        affected order.
      </p>
      <p>
        Order value is defined as ‘quantity * (merchant price + merchant
        shipping)’.
      </p>
      <p>
        Addendum: Effective August 6, 2019 8PM Pacific Time, orders that are
        found to have been affected by manipulated reviews and/or ratings are
        subject to be penalized up to {formatCurrency(10, "USD")}* per affected
        order.
      </p>

      <p className={css(styles.subsectionEnd)}>
        <Link href={zendeskURL("360013668033")} openInNewTab>
          See examples and learn more
        </Link>
      </p>
    </PolicySubSection>
  );
};

const useStylesheet = () =>
  useMemo(
    () =>
      StyleSheet.create({
        subsectionEnd: {
          marginBottom: 0,
        },
      }),
    []
  );

export default observer(Section12);
