//
//  toolkit/illustration.ts
//  Project-Lego
//
//  Created by Sola Ogunsakin on 2/19/19.
//  Copyright © 2019-present ContextLogic Inc. All rights reserved.
//
import cnmerchant1URL from "@assets/img/cn-merchant-one.jpg";
import merchant1URL from "@assets/img/merchant-one.jpg";
import merchant2URL from "@assets/img/merchant-two.png";
import merchant3URL from "@assets/img/merchant-three.jpg";
import merchant4URL from "@assets/img/merchant-four.jpg";
import fbwstep01URL from "@assets/img/fbw/fbw-step-01.jpg";
import fbwstep02URL from "@assets/img/fbw/fbw-step-02.jpg";
import fbwstep03URL from "@assets/img/fbw/fbw-step-03.jpg";
import fbwstep04URL from "@assets/img/fbw/fbw-step-04.jpg";
import fbwstep05URL from "@assets/img/fbw/fbw-step-05.jpg";
import fbwstep06URL from "@assets/img/fbw/fbw-step-06.jpg";
import fbwstep07URL from "@assets/img/fbw/fbw-step-07.jpg";
import fbwstep08URL from "@assets/img/fbw/fbw-step-08.jpg";
import fbwstep09URL from "@assets/img/fbw/fbw-step-09.jpg";
import fbsRecommendationSectionURL from "@assets/img/fbs/recommendation-section.png";
import paypalUrl from "@assets/img/erp_onboarding/paypal.png";
import apiPartnerURL from "@assets/img/erp_onboarding/api-partner.png";
import fourthlineLogoDarkURL from "@assets/img/fourthline-logo-dark.png";
import poweredByGoogleURL from "@assets/img/powered-by-google.png";
import mockMobileHeaderURL from "@assets/img/mock-mobile-header.png";
import wishClipsBannerURL from "@assets/img/wish-clips-banner.png";
import cnBusinessLicenseExampleURL from "@assets/img/cn-business-license-example.png";

// merchant summit 2021 assets
import externalTwitterURL from "@assets/img/merchant-summit/icons/external-twitter.svg";
import externalFacebookURL from "@assets/img/merchant-summit/icons/external-facebook.svg";
import externalInstagramURL from "@assets/img/merchant-summit/icons/external-instagram.svg";
import externalPinterestURL from "@assets/img/merchant-summit/icons/external-pinterest.svg";
import externalTiktokURL from "@assets/img/merchant-summit/icons/external-tiktok.svg";
import externalYoutubeURL from "@assets/img/merchant-summit/icons/external-youtube.svg";
import externalLinkedinURL from "@assets/img/merchant-summit/icons/external-linkedin.svg";
import iconEnhancedPlatformURL from "@assets/img/merchant-summit/icons/icon-enhanced-platform.svg";
import iconGlobalSupportURL from "@assets/img/merchant-summit/icons/icon-global-support.svg";
import iconMerchantGrowthInitiativesURL from "@assets/img/merchant-summit/icons/icon-merchant-growth-initiatives.svg";
import iconWishCommunityPillarsURL from "@assets/img/merchant-summit/icons/icon-wish-community-pillars.svg";
import iconWishFulfillmentURL from "@assets/img/merchant-summit/icons/icon-wish-fulfillment.svg";
import iconWishInsightsURL from "@assets/img/merchant-summit/icons/icon-wish-insights.svg";
import iconWishStandardsURL from "@assets/img/merchant-summit/icons/icon-wish-standards.svg";
import logoEquickURL from "@assets/img/merchant-summit/icons/logo-equick.png";
import logoLianlianglobalURL from "@assets/img/merchant-summit/icons/logo-lianlianglobal.png";
import logoSfinternationalURL from "@assets/img/merchant-summit/icons/logo-sfinternational.png";
import logoSunyouURL from "@assets/img/merchant-summit/icons/logo-sunyou.png";
import logoTopyouURL from "@assets/img/merchant-summit/icons/logo-topyou.png";
import logoUmfURL from "@assets/img/merchant-summit/icons/logo-umf.png";
import logoWiseexpressURL from "@assets/img/merchant-summit/icons/logo-wiseexpress.png";
import logoYunexpressURL from "@assets/img/merchant-summit/icons/logo-yunexpress.png";
import logoYwwenexpressURL from "@assets/img/merchant-summit/icons/logo-ywwenexpress.png";
import headerMobileURL from "@assets/img/merchant-summit/landing/mobile/header-mobile.svg";
import merchantConferenceCnBannerMobileURL from "@assets/img/merchant-summit/landing/mobile/merchant-conference-cn-banner-mobile.svg";
import videoBackgroundMobileURL from "@assets/img/merchant-summit/landing/mobile/video-background-mobile.svg";
import videoBackgroundMobileImageURL from "@assets/img/merchant-summit/landing/mobile/video-background-mobile.png";
import summitBannerMobileURL from "@assets/img/merchant-summit/landing/mobile/summit-banner-mobile.png";
import blueBackgroundURL from "@assets/img/merchant-summit/landing/web/blue-background.svg";
import footerBackgroundURL from "@assets/img/merchant-summit/landing/web/footer-background.svg";
import greyBackgroundURL from "@assets/img/merchant-summit/landing/web/grey-background.svg";
import headerImageWebURL from "@assets/img/merchant-summit/landing/web/header-image-web.svg";
import summitBannerWebURL from "@assets/img/merchant-summit/landing/web/summit-banner-web.png";
import videoBackgroundWebURL from "@assets/img/merchant-summit/landing/web/video-background-web.png";
import merchantConferenceChinaBannerURL from "@assets/img/merchant-summit/landing/web/merchant-conference-china-banner.png";
import signupBackgroundURL from "@assets/img/merchant-summit/landing/web/signup-background.svg";
import videoBackgroundImageWebURL from "@assets/img/merchant-summit/landing/web/video-background-image-web.svg";
import teaserHeaderMobileURL from "@assets/img/merchant-summit/teaser/mobile/teaser-header-mobile.png";
import teaserHeaderURL from "@assets/img/merchant-summit/teaser/web/teaser-header.png";
import pictureDanURL from "@assets/img/merchant-summit/videos/pictures/dan.png";
import pictureEmmaURL from "@assets/img/merchant-summit/videos/pictures/emma.png";
import pictureFarhangURL from "@assets/img/merchant-summit/videos/pictures/farhang.jpg";
import pictureSarahURL from "@assets/img/merchant-summit/videos/pictures/sarah.jpg";
import pictureTarunURL from "@assets/img/merchant-summit/videos/pictures/tarun.jpg";
import pictureVivianURL from "@assets/img/merchant-summit/videos/pictures/vivian.jpg";

/* SVGs */
import lightBulbYellowURL from "@assets/img/illustration-light-bulb-yellow.svg";
import lightBulbBackgroundColorYellowURL from "@assets/img/light-bulb-background-color-yellow.svg";
import moneyIconURL from "@assets/img/money-icon.svg";
import fbsIntro1URL from "@assets/img/fbw/benefit-01.svg";
import fbsIntro2URL from "@assets/img/fbw/benefit-02.svg";
import fbsIntro3URL from "@assets/img/fbw/benefit-03.svg";
import fbsPerformanceHeaderURL from "@assets/img/fbs/fbs-dashboard-header.svg";
import productBoostFBWFreeURL from "@assets/img/product-boost/pb-fbw-illustration-free.svg";
import productBoostFBWDiscountURL from "@assets/img/product-boost/pb-fbw-illustration-discount.svg";
import whyFBSURL from "@assets/img/fbs/why-fbs.svg";
import fbsEmptyStateURL from "@assets/img/fbs/empty-state.svg";
import lightBulbURL from "@assets/img/illustration-light-bulb.svg";
import redBulbURL from "@assets/img/red-bulb.svg";
import finesHeaderURL from "@assets/img/fines-header.svg";
import greenCheckmarkURL from "@assets/img/green-checkmark-hollow.svg";
import finesPolicyHeaderURL from "@assets/img/fines-policies-header.svg";
import calculatingURL from "@assets/img/illustration-tax-header.svg";
import manCalculatingURL from "@assets/img/illustration-tax-header.svg";
import signatureURL from "@assets/img/illustration-submit-tax-settings.svg";
import productBoostHeaderURL from "@assets/img/productboost-header-icon.svg";
import impressionBoosterURL from "@assets/img/illustration-impression-booster.svg";
import salesBoosterURL from "@assets/img/illustration-sales-booster.svg";
import wishExpressTruckURL from "@assets/img/wish-express.svg";
import wishExpressBlueBoxURL from "@assets/img/wish-express-blue-box.svg";
import activeMerchantStandingURL from "@assets/img/merchant-standing/active.svg";
import uploadProductIconURL from "@assets/img/upload-product-icon.svg";
import goldMerchantStandingURL from "@assets/img/merchant-standing/gold.svg";
import platinumMerchantStandingURL from "@assets/img/merchant-standing/platinum.svg";
import silverMerchantStandingURL from "@assets/img/merchant-standing/silver.svg";
import underReviewMerchantStandingURL from "@assets/img/merchant-standing/under-review.svg";
import fbwHeaderURL from "@assets/img/fbw/fbw-header.svg";
import fbwDashboardHeaderURL from "@assets/img/fbw/fbw-dashboard-header.svg";
import fbwShippingPriceDropURL from "@assets/img/fbw/shipping-price-drop.svg";
import gmvURL from "@assets/img/fbw/gmv.svg";
import orderURL from "@assets/img/fbw/orders.svg";
import soldURL from "@assets/img/fbw/sold.svg";
import refundURL from "@assets/img/fbw/refunded.svg";
import refundsURL from "@assets/img/refunds.svg";
import fbwURL from "@assets/img/fbw/fbw.svg";
import fbw2Url from "@assets/img/fbw/fbw2.svg";
import lowInStockURL from "@assets/img/fbw/low-in-stock.svg";
import filterURL from "@assets/img/filters.svg";
import filterBlueURL from "@assets/img/filters-wish-blue.svg";
import searchURL from "@assets/img/search.svg";
import disputeSuccessURL from "@assets/img/illustration-dispute.svg";
import disputeRejectedURL from "@assets/img/dispute-rejected.svg";
import disputePartiallyRejectedURL from "@assets/img/dispute-partial-accept.svg";
import submitDisputeURL from "@assets/img/illustration-submit-dispute.svg";
import perfHeaderURL from "@assets/img/perf-overview-header.svg";
import blackArrowUpURL from "@assets/img/blackarrowup.svg";
import blackArrowDownURL from "@assets/img/blackarrowdown.svg";
import greenArrowUpURL from "@assets/img/green-arrow-up.svg";
import redArrowDownURL from "@assets/img/red-arrow-down.svg";
import gdecreaseArrowURL from "@assets/img/greendecreasearrow.svg";
import gincreaseArrowURL from "@assets/img/greenincreasearrow.svg";
import rdecreaseArrowURL from "@assets/img/reddecreasearrow.svg";
import rincreaseArrowURL from "@assets/img/redincreasearrow.svg";
import productBoostDarkBlueUrl from "@assets/img/product-boost/product-boost-dark-blue.svg";
import productBoostTransactionURL from "@assets/img/productboost-transaction-header.svg";
import productBoostPhoneURL from "@assets/img/product-boost/edit-campaign-header.svg";
import productBoostDetailHeaderURL from "@assets/img/product-boost/campaign-detail-header.svg";
import productBoostCampaignListHeaderURL from "@assets/img/product-boost/campaign-list-header.svg";
import productBoostCampaignSpendURL from "@assets/img/product-boost/campaign-spend.svg";
import productBoostSpendToGMVURL from "@assets/img/product-boost/spend-to-gmv.svg";
import productBoostMaxBoostURL from "@assets/img/product-boost/max-boost.svg";
import productBoostBonusBudgetURL from "@assets/img/product-boost/bonus-budget.svg";
import productBoostKeywordsURL from "@assets/img/product-boost/keyword-header-icon.svg";
import productBoostHomepageModalLogoURL from "@assets/img/product-boost/pb-homepage-modal-illustration.svg";
import productBoostHomepageBudgetURL from "@assets/img/product-boost/pb-homepage-modal-increase-budget.svg";
import productBoostCostCalculationBannerURL from "@assets/img/product-boost/cost-calculation-banner.svg";
import wishExpressWithTextURL from "@assets/img/wish-express-logo-with-wording.svg";
import illustration1URL from "@assets/img/we-splash-illustration-01.svg";
import illustration2URL from "@assets/img/we-splash-illustration-02.svg";
import illustration3URL from "@assets/img/we-splash-illustration-03.svg";
import illustration4URL from "@assets/img/we-splash-illustration-04.svg";
import illustration5URL from "@assets/img/we-splash-illustration-05.svg";
import illustration6URL from "@assets/img/we-splash-illutstration-6.svg";
import cnmerchant2URL from "@assets/img/cn-merchant-two.svg";
import legoURL from "@assets/img/lego.svg";
import wishExpressWithoutTextURL from "@assets/img/wish-express-logo-without-wording.svg";
import impressionIconURL from "@assets/img/eye.svg";
import paidImpressionIconURL from "@assets/img/eye-dollar.svg";
import maxBoostImpressionIconURL from "@assets/img/eye-boost.svg";
import orderIconURL from "@assets/img/order-icon.svg";
import dollarIconURL from "@assets/img/dollar.svg";
import campaignIconURL from "@assets/img/campaign.svg";
import calendarIconURL from "@assets/img/calendar.svg";
import fulfillmentLogoURL from "@assets/img/fulfillment-by-wish-logo.svg";
import createHeaderURL from "@assets/img/fbw/createHeader.svg";
import addIconURL from "@assets/img/fbw/add-icon.svg";
import recomIconURL from "@assets/img/fbw/recom-icon.svg";
import fbwConfirmURL from "@assets/img/fbw/fbwConfirm.svg";
import starURL from "@assets/img/fbw/star.svg";
import bagURL from "@assets/img/fbw/bag.svg";
import warehouseURL from "@assets/img/fbw/warehouse.svg";
import wishForMerchantsURL from "@assets/img/wish-for-merchants-logo.svg";
import laptopBagOfMoneyURL from "@assets/img/laptop-bag-money-credit-card.svg";
import quoteURL from "@assets/img/quote-icon.svg";
import merchantLandingURL from "@assets/img/landing-header-illustration.svg";
import landingIllustrationLeftURL from "@assets/img/landing-header-illustration-left.svg";
import landingIllustrationRightURL from "@assets/img/landing-header-illustration-right.svg";
import globalPhoneLocationsURL from "@assets/img/globe-phone-locations.svg";
import merchantLandingSmallerURL from "@assets/img/landing-header-illustration-smaller.svg";
import facebookURL from "@assets/img/iconography/facebook_colored@1x.svg";
import facebookOutlinedURL from "@assets/img/iconography/facebook_outlined@1x.svg";
import facebookFilledURL from "@assets/img/iconography/facebook_filled@1x.svg";
import instagramURL from "@assets/img/iconography/instagram_colored@1x.svg";
import instagramOutlinedURL from "@assets/img/iconography/instagram_outlined@1x.svg";
import instagramFilledURL from "@assets/img/iconography/instagram_filled@1x.svg";
import twitterURL from "@assets/img/iconography/twitter_colored@1x.svg";
import twitterOutlinedURL from "@assets/img/iconography/twitter_outlined@1x.svg";
import twitterFilledURL from "@assets/img/iconography/twitter_filled@1x.svg";
import youtubeURL from "@assets/img/iconography/youtube_colored@1x.svg";
import youtubeOutlinedURL from "@assets/img/iconography/youtube_outlined@1x.svg";
import youtubeFilledURL from "@assets/img/iconography/youtube_filled@1x.svg";
import cartURL from "@assets/img/iconography/cart@1x.svg";
import customerURL from "@assets/img/iconography/customer@1x.svg";
import warehouse2URL from "@assets/img/iconography/warehouse@1x.svg";
import awardFilledURL from "@assets/img/iconography/award_filled@1x.svg";
import awardOutlinedURL from "@assets/img/iconography/award_outlined@1x.svg";
import wishLogoBlueURL from "@assets/img/wish-logo-blue.svg";
import wishLogoWhiteURL from "@assets/img/wish-logo-white.svg";
import epcUrl from "@assets/img/epc/epc.svg";
import epcFastPaymentsURL from "@assets/img/epc/epc-fast-payments.svg";
import thirdPartyBrandedGoodsDeclarationURL from "@assets/img/third-party-branded-goods-declaration-header.svg";
import returnsTruckUrl from "@assets/img/returns-truck.svg";
import returnsURL from "@assets/img/returns.svg";
import coinsURL from "@assets/img/coins.svg";
import greyoutCoinsURL from "@assets/img/greyout_coins.svg";
import fbwInventoryListingURL from "@assets/img/fbw/fbw-inventory-listing.svg";
import cardTextureURL from "@assets/img/card-texture-01.svg";
import productBoostRocketHeartbreakURL from "@assets/img/product-boost/turn-on-auto-renew.svg";
import productBoostRocketURL from "@assets/img/product-boost/turn-off-auto-renew.svg";
import advancedLogisticsUrl from "@assets/img/advanced-logistics-program.svg";
import calendarBlueURL from "@assets/img/this-week.svg";
import wishPostURL from "@assets/img/wish-post.svg";
import epcExplanationStep1URL from "@assets/img/epc/explanation-step-1.svg";
import epcExplanationStep2URL from "@assets/img/epc/explanation-step-2.svg";
import epcExplanationStep3URL from "@assets/img/epc/explanation-step-3.svg";
import error403URL from "@assets/img/error-403.svg";
import error404URL from "@assets/img/error-404.svg";
import error500URL from "@assets/img/error-500.svg";
import lockEmptyStateURL from "@assets/img/lock-empty-state.svg";
import settingsAppStoreBannerURL from "@assets/img/merchant-appstore-banner.svg";
import shapesEmptyStateURL from "@assets/img/shapes-empty-state.svg";
import appNoLogoURL from "@assets/img/app-no-logo.svg";
import erpPartnerNoLogoURL from "@assets/img/erp-partner-no-logo.svg";
import fbwRecommendationSectionURL from "@assets/img/fbw/recommendation-section.svg";
import submitTrueBrandRequestConfirmationURL from "@assets/img/submit-true-brand-request-confirmation-illustration.svg";
import merchantInvitationHeaderURL from "@assets/img/merchant-invitation-header.svg";
import trueBrandDirectoryHeaderURL from "@assets/img/true-brand-directory-header.svg";
import merchantTrueBrandRequestsHeaderURL from "@assets/img/merchant-brand-requests-illustration.svg";
import absHeaderURL from "@assets/img/brand/branded-products/absb/abs_header_illustration.svg";
import policyArchiveHeaderURL from "@assets/img/policy/policy-archive-header.svg";
import ladyHoldingPackageURL from "@assets/img/lady-holding-package.svg";
import reviewHeaderURL from "@assets/img/review-header-illustration.svg";
import houseWithFlagURL from "@assets/img/house-with-flag.svg";
import developerLandingIllustrationURL from "@assets/img/developer-landing-illustration.svg";
import developerNavigationIllustrationURL from "@assets/img/developer-navigation-illustration.svg";
import resellerAgreementIllustrationURL from "@assets/img/reseller-agreement-illustration.svg";
import developerMerchantsIllustrationURL from "@assets/img/developer-merchants-illustration.svg";
import developerDeskIllustrationURL from "@assets/img/developer-desk-illustration.svg";
import fbwFeeURL from "@assets/img/fbw/fbw-fees-illustration.svg";
import paymentIconURL from "@assets/img/payments-icon.svg";
import earlyPaymentEligibleBannerImgURL from "@assets/img/early_payment/early_payment_eligible_banner.svg";
import earlyPaymentNotEligibleBannerImgURL from "@assets/img/early_payment/early_payment_not_eligible_banner.svg";
import wishLogoInkURL from "@assets/img/wish-logo-ink.svg";
import houseWithPinpointsURL from "@assets/img/epc/enroll_product_banner.svg";
import womanUsingTelescopeURL from "@assets/img/woman-using-telescope.svg";
import idVerificationURL from "@assets/img/id-verification.svg";
import blueWishHouseURL from "@assets/img/blue-wish-house.svg";
import buildingsUnderDomeURL from "@assets/img/buildings-under-dome.svg";
import potentialUnlockedBannerURL from "@assets/img/potential-unlocked-banner.svg";
import computerPhoneOnDeskURL from "@assets/img/computer-phone-on-desk.svg";
import blueHouseURL from "@assets/img/blue-house.svg";
import blueHouseWithDecorationURL from "@assets/img/blue-house-with-decoration.svg";
import manHoldingBoxURL from "@assets/img/man-holding-box.svg";
import manHoldingIdURL from "@assets/img/man-holding-id.svg";
import sizeChartURL from "@assets/img/size-chart.svg";
import sizeChartBannerImgURL from "@assets/img/size-chart-banner.svg";
import boxesInFrontOfEarthURL from "@assets/img/boxes-in-front-of-earth.svg";
import merchantPlusHomeURL from "@assets/img/merchant-plus/home.svg";
import merchantPlusAddProductsTaskURL from "@assets/img/merchant-plus/onboarding/add-products-task.svg";
import merchantPlusUploadProductsHowToURL from "@assets/img/merchant-plus/upload-products-howto.svg";
import merchantPlusVerifyEmailTaskURL from "@assets/img/merchant-plus/onboarding/verify-email-task.svg";
import plantLaptopHomeBoxURL from "@assets/img/plant-laptop-home-box.svg";
import yellowTruckBoxesInsideURL from "@assets/img/merchant-plus/yellow-truck-boxes-inside.svg";
import userOnPhoneLoveHandbagURL from "@assets/img/merchant-plus/user-on-phone-love-handbag.svg";
import merchantPlus2FATaskURL from "@assets/img/merchant-plus/onboarding/2fa-task.svg";
import merchantPlusSetupPaymentsTaskURL from "@assets/img/merchant-plus/onboarding/setup-payments-task.svg";
import merchantPlusSetupShippingTaskURL from "@assets/img/merchant-plus/onboarding/setup-shipping-task.svg";
import merchantPlusMarkOrdersShippedTaskURL from "@assets/img/merchant-plus/onboarding/mark-orders-shipped-task.svg";
import merchantPlus2FAOnURL from "@assets/img/merchant-plus/2fa-on-illustration.svg";
import merchantPlusVacationModeOnURL from "@assets/img/merchant-plus/vacation-mode-illustration.svg";
import merchantPlusVacationModeOffURL from "@assets/img/merchant-plus/vacation-mode-off-illustration.svg";
import productCatalogURL from "@assets/img/merchant-plus/product-catalog.svg";
import absbAuthorizedResellerIllustrationURL from "@assets/img/brand/branded-products/absb/authorized_reseller_illustration.svg";
import absbBrandOwnerIllustrationURL from "@assets/img/brand/branded-products/absb/brand_owner_illustration.svg";
import absbUnauthorizedResellerIllustrationURL from "@assets/img/brand/branded-products/absb/unauthorized_reseller_illustration.svg";
import boxWithBlueRibbonURL from "@assets/img/merchant-plus/box-with-blue-ribbon.svg";
import notepadListURL from "@assets/img/merchant-plus/notepad-list.svg";
import fulfillmentChecklistWithBoxURL from "@assets/img/merchant-plus/fulfillment-checklist-with-box.svg";
import laptopPlantBoxesHomescreenWishURL from "@assets/img/merchant-plus/laptop-plant-boxes-homescreen-wish.svg";
import confirmedDeliveryCheckmarkURL from "@assets/img/merchant-plus/confirmed-delivery-checkmark.svg";
import preorderOnboardingLogoURL from "@assets/img/pre-order-onboarding-logo.svg";
import preorderOnboardingContactLogoURL from "@assets/img/lady-holding-package-no-side-package.svg";
import preorderProcessingOrderLogoURL from "@assets/img/pre-order-processing-order-logo.svg";
import stackedBoxesURL from "@assets/img/merchant-plus/stacked-boxes.svg";
import merchantPlusDeleteAllDevicesURL from "@assets/img/merchant-plus/delete-all-devices-illustration.svg";
import emptyImageURL from "@assets/img/merchant-plus/emptyimage.svg";
import crownGrayURL from "@assets/img/merchant-plus/crown.svg";
import clockCircleArrowURL from "@assets/img/merchant-plus/clock-circle-arrow.svg";
import brandedProductsHeaderURL from "@assets/img/brand/branded-products/branded-products-header.svg";
import brandedProductVerificationSectionURL from "@assets/img/brand/branded-products/branded-product-verification-section.svg";
import productBoostSectionURL from "@assets/img/brand/branded-products/product-boost-section.svg";
import brandDirectorySectionURL from "@assets/img/brand/branded-products/brand-directory-section.svg";
import absbSectionURL from "@assets/img/brand/branded-products/absb-section.svg";
import gmvIconURL from "@assets/img/brand/branded-products/gmv-icon.svg";
import ordersIconURL from "@assets/img/brand/branded-products/orders-icon.svg";
import impressionsIconURL from "@assets/img/brand/branded-products/impressions-icon.svg";
import verifyEmailIllustrationURL from "@assets/img/brand/brand-partner/home-page/verify-email-illustration.svg";
import verifyEmailBannerURL from "@assets/img/brand/brand-partner/home-page/verify-email-banner.svg";
import enrollBrandIllustrationURL from "@assets/img/brand/brand-partner/home-page/enroll-brand-illustration.svg";
import searchReportIllustrationURL from "@assets/img/brand/brand-partner/home-page/search-report-illustration.svg";
import mainContentIllustrationURL from "@assets/img/brand/brand-partner/landing-page/main-content-illustration.svg";
import enforceBrandIconURL from "@assets/img/brand/brand-partner/landing-page/enforce-brand-icon.svg";
import searchListingsIconURL from "@assets/img/brand/brand-partner/landing-page/search-listings-icon.svg";
import reportViolationsIconURL from "@assets/img/brand/brand-partner/landing-page/report-violations-icon.svg";
import wishExpressTruckSidewayskURL from "@assets/img/merchant-plus/wish-express-truck-sideways.svg";
import merchantPlusWishExpressHeaderURL from "@assets/img/merchant-plus/plus-we-header.svg";
import checkedEyeURL from "@assets/img/merchant-plus/checked-eye.svg";
import paymentCardURL from "@assets/img/merchant-plus/payment-card.svg";
import palaceBlueBulbURL from "@assets/img/merchant-plus/palace-blue-bulb.svg";
import rocketPurpleBackgroundURL from "@assets/img/merchant-plus/rocket-purple-background.svg";
import wishAppTopBarURL from "@assets/img/merchant-plus/wish-app-topbar.png";
import adBadgeURL from "@assets/img/merchant-plus/ad-icon.svg";

import storeShopperURL from "@assets/img/merchant-plus/store-shopper.svg";
import productsCloudURL from "@assets/img/merchant-plus/products-cloud.svg";
import restrictedProductPlantAndPlantSeedsRawURL from "@assets/img/policy/restricted-product/plant_and_plant_seeds_raw.svg";
import restrictedProductVitaminsRawURL from "@assets/img/policy/restricted-product/vitamins_raw.svg";
import restrictedProductBeveragesRawURL from "@assets/img/policy/restricted-product/beverages_raw.svg";
import restrictedProductFoodRawURL from "@assets/img/policy/restricted-product/food_raw.svg";
import restrictedProductPetFoodRawURL from "@assets/img/policy/restricted-product/pet_food_raw.svg";
import restrictedProductMedicationsRawURL from "@assets/img/policy/restricted-product/medications_raw.svg";
import restrictedProductCarSeatsRawURL from "@assets/img/policy/restricted-product/car_seats_raw.svg";
import restrictedProductCarriersRawURL from "@assets/img/policy/restricted-product/carriers_raw.svg";
import restrictedProductSeatBeltRawURL from "@assets/img/policy/restricted-product/seat_belt_raw.svg";
import restrictedProductWarrantiesRawURL from "@assets/img/policy/restricted-product/warranties_raw.svg";
import restrictedProductPlantAndPlantSeedsCircleURL from "@assets/img/policy/restricted-product/plant_and_plant_seeds_circle.svg";
import restrictedProductVitaminsCircleURL from "@assets/img/policy/restricted-product/vitamins_circle.svg";
import restrictedProductBeveragesCircleURL from "@assets/img/policy/restricted-product/beverages_circle.svg";
import restrictedProductFoodCircleURL from "@assets/img/policy/restricted-product/food_circle.svg";
import restrictedProductPetFoodCircleURL from "@assets/img/policy/restricted-product/pet_food_circle.svg";
import restrictedProductMedicationsCircleURL from "@assets/img/policy/restricted-product/medications_circle.svg";
import restrictedProductCarSeatsCircleURL from "@assets/img/policy/restricted-product/car_seats_circle.svg";
import restrictedProductCarriersCircleURL from "@assets/img/policy/restricted-product/carriers_circle.svg";
import restrictedProductSeatBeltCircleURL from "@assets/img/policy/restricted-product/seat_belt_circle.svg";
import restrictedProductWarrantiesCircleURL from "@assets/img/policy/restricted-product/warranties_circle.svg";
import restrictedProductPlantAndPlantSeedsColorURL from "@assets/img/policy/restricted-product/plant_and_plant_seeds_color.svg";
import restrictedProductVitaminsColorURL from "@assets/img/policy/restricted-product/vitamins_color.svg";
import restrictedProductBeveragesColorURL from "@assets/img/policy/restricted-product/beverages_color.svg";
import restrictedProductFoodColorURL from "@assets/img/policy/restricted-product/food_color.svg";
import restrictedProductPetFoodColorURL from "@assets/img/policy/restricted-product/pet_food_color.svg";
import restrictedProductMedicationsColorURL from "@assets/img/policy/restricted-product/medications_color.svg";
import restrictedProductCarSeatsColorURL from "@assets/img/policy/restricted-product/car_seats_color.svg";
import restrictedProductCarriersColorURL from "@assets/img/policy/restricted-product/carriers_color.svg";
import restrictedProductSeatBeltColorURL from "@assets/img/policy/restricted-product/seat_belt_color.svg";
import restrictedProductWarrantiesColorURL from "@assets/img/policy/restricted-product/warranties_color.svg";
import restrictedProductURL from "@assets/img/policy/restricted-product/restricted_product_illustration.svg";
import weeklyDisbBannerImageURL from "@assets/img/weekly-payments-calendar.svg";
import productUploadBannerImageURL from "@assets/img/product-upload-header.svg";
import merchantPlusSellerValidationTaskURL from "@assets/img/merchant-plus/onboarding/seller-validation-task.svg";
import productDemoBannerImageURL from "@assets/img/product-demo-banner-image.svg";
import cloudUploadURL from "@assets/img/cloud-upload.svg";
import demoBoxCircleURL from "@assets/img/demo-box-circle.svg";
import phoneDimensionsCircleURL from "@assets/img/phone-dimensions-circle.svg";
import clockCircleURL from "@assets/img/clock-circle.svg";
import getItOnGooglePlayURL from "@assets/img/get-it-on-google-play.svg";
import downloadOnTheAppStoreURL from "@assets/img/download-on-the-app-store.svg";
import blueCheckmarkURL from "@assets/img/blue-checkmark.svg";
import darkCheckmarkURL from "@assets/img/dark-checkmark.svg";
import whiteCheckmarkURL from "@assets/img/white-checkmark.svg";
import closeURL from "@assets/img/close.svg";
import closeWhiteRoundedURL from "@assets/img/close-white-rounded.svg";
import thumbsUpDarkURL from "@assets/img/thumbs-up-dark.svg";
import thumbsUpWhiteURL from "@assets/img/thumbs-up-white.svg";
import thumbsDownDarkURL from "@assets/img/thumbs-down-dark.svg";
import thumbsDownWhiteURL from "@assets/img/thumbs-down-white.svg";
import externalLinkURL from "@assets/img/external-link.svg";
import paperAirplaneURL from "@assets/img/paper-airplane.svg";
import locationMarkerURL from "@assets/img/location-marker.svg";
import editWishBlueURL from "@assets/img/iconography/edit_24x24_wish_blue.svg";
import documentURL from "@assets/img/document.svg";
import closedPackageURL from "@assets/img/closed-package.svg";
import truckOutlineURL from "@assets/img/truck-outline.svg";
import boxesURL from "@assets/img/boxes.svg";
import yellowExclamationURL from "@assets/img/yellow-exclamation.svg";
import warehouseOverviewBannerImageURL from "@assets/img/warehouse-overview-banner-image.svg";
import locationMarkerGreyURL from "@assets/img/location-marker-grey.svg";
import locationMarkerYellowURL from "@assets/img/location-marker-yellow.svg";
import locationMarkerRedURL from "@assets/img/location-marker-red.svg";
import redXURL from "@assets/img/red-x.svg";
import warningYellowURL from "@assets/img/warning-yellow.svg";
import refundAssuranceURL from "@assets/img/product-boost/refund-assurance.svg";
import socialAdsBoostURL from "@assets/img/product-boost/social-ads-boost.svg";
import supportAgentURL from "@assets/img/support-agent.svg";
import starFilledURL from "@assets/img/star-filled.svg";
import starUnfilledURL from "@assets/img/star-unfilled.svg";
import starHalfFilledURL from "@assets/img/star-half-filled.svg";
import bannerUploadProductsURL from "@assets/img/banner-upload-products.svg";
import bannerAddProductVariationsURL from "@assets/img/banner-add-product-variations.svg";
import performanceOverviewURL from "@assets/img/performance-overview.svg";
import grayTrashURL from "@assets/img/gray-trash.svg";
import merchantCsHubHeaderURL from "@assets/img/merchant-cs-hub.svg";
import customerSupportURL from "@assets/img/customer-support.svg";
import darkGreenCheckmarkURL from "@assets/img/dark-green-checkmark.svg";
import darkGreenCheckmarkFilledURL from "@assets/img/dark-green-checkmark-filled.svg";
import grayDashURL from "@assets/img/gray-dash.svg";
import chevronRightBlueURL from "@assets/img/chevron-right-blue.svg";
import cheeringEuURL from "@assets/img/illustration-cheering-eu.svg";
import palaceBlueDisputeURL from "@assets/img/palace-blue-dispute.svg";
import upsLogoURL from "@assets/img/ups-logo.svg";
import personUsingBinocularsURL from "@assets/img/person-using-binoculars.svg";
import productListingPlanHeaderURL from "@assets/img/product-listing-plan-header.svg";
import productListingPlanAboutURL from "@assets/img/product-listing-plan-about.svg";
import disableURL from "@assets/img/disable.svg";
import shippingLabelBoxURL from "@assets/img/shipping-label-box.svg";
import shippingLabelEnvelopeURL from "@assets/img/shipping-label-envelope.svg";
import uspsLogoURL from "@assets/img/usps-logo.png";
import wssSplashRibbonURL from "@assets/img/wss-splash-ribbon.svg";
import wssSplashRibbonMobileURL from "@assets/img/wss-splash-ribbon-mobile.svg";
import wssPlatinumBadgeURL from "@assets/img/wss-platinum-badge.svg";
import wssGoldBadgeURL from "@assets/img/wss-gold-badge.svg";
import wssSilverBadgeURL from "@assets/img/wss-silver-badge.svg";
import wssBronzeBadgeURL from "@assets/img/wss-bronze-badge.svg";
import wssScreenshotURL from "@assets/img/wss-screenshot.svg";
import wishAppImageURL from "@assets/img/wish-app-image.svg";
import wishStandardsBannerURL from "@assets/img/wish-standards-banner.svg";
import wpsURL from "@assets/img/wps.svg";
import warningFilledURL from "@assets/img/warning-filled.svg";
import wssUnratedBadgeURL from "@assets/img/wss-unrated-badge.svg";
import rightArrowLongURL from "@assets/img/right-arrow-long.svg";
import badgeCheckmarkURL from "@assets/img/badge-checkmark.svg";
import merchantBlogBannerURL from "@assets/img/merchant-blog-banner.svg";
import mfpHeaderURL from "@assets/img/mfp/mfp-header.svg";
import topSellerURL from "@assets/img/top-seller.svg";
import productCsvHeaderURL from "@assets/img/product-csv-header.svg";
import newProductPageBannerURL from "@assets/img/new-product-page-banner.svg";
import wURL from "@assets/img/W.svg";
import noActivePromotionsURL from "@assets/img/no-active-promotions.svg";
import mfpCardBgDiscountURL from "@assets/img/mfp-card-bg-discount.svg";
import mfpCardBgFlashSaleURL from "@assets/img/mfp-card-bg-flash-sale.svg";
import lightningFilledURL from "@assets/img/zeus/lightning-filled.svg";
import tagFilledURL from "@assets/img/zeus/tag-filled.svg";
import tagFilledGreyURL from "@assets/img/zeus/tag-filled-grey.svg";
import mfpPriceOnlyIllustrationURL from "@assets/img/mfp-price-only-illustration.svg";
import mfpHeaderIllustrationURL from "@assets/img/mfp-header-illustration.svg";
import mfpHowToCreatePromotionURL from "@assets/img/mfp-how-to-create-promotion.svg";
import mfpNeedMoreHelpURL from "@assets/img/mfp-need-more-help.svg";
import mfpNoPromotionsEverURL from "@assets/img/mfp-no-promotions-ever.svg";
import mfpPriceOnlyExampleProductURL from "@assets/img/mfp-price-only-example-product.jpg";
import taxFormCalculatorURL from "@assets/img/tax-form-calculator.svg";
import videoResourceHubBannerImageURL from "@assets/img/video-resource-hub-banner-image.svg";
import videoManagementHubBannerImageURL from "@assets/img/video-management-hub-banner-image.svg";
import oneExclamationURL from "@assets/img/one-exclamation.svg";
import twoExclamationURL from "@assets/img/two-exclamation.svg";
import qualifiedCarriersURL from "@assets/img/qualified-carriers.svg";
import videoFilmBannerURL from "@assets/img/video-film-illustration.svg";
import videoFilmIconURL from "@assets/img/video-film-icon.svg";
import holdingPhoneBannerURL from "@assets/img/holding-phone-banner.svg";
import merchantFundedPromotionsURL from "@assets/img/merchant-funded-promotions.svg";
import videosURL from "@assets/img/videos.svg";
import wishStandardsURL from "@assets/img/wish-standards.svg";
import blankWishClipExampleScreenshotURL from "@assets/img/blank-wish-clip-example-screenshot.svg";
import verticalOrientationCircleIconURL from "@assets/img/vertical-orientation-circle-icon.svg";
import highResCircleIconURL from "@assets/img/high-res-circle-icon.svg";
import timerCircleIconURL from "@assets/img/timer-circle-icon.svg";
import phoneCircleIconURL from "@assets/img/phone-circle-icon.svg";
import muteCircleIconURL from "@assets/img/mute-circle-icon.svg";
import givingHandCircleIconURL from "@assets/img/giving-hand-circle-icon.svg";
import homeGettingImpressionsURL from "@assets/img/home-getting-impressions.svg";
import videoAnalyticsMissingURL from "@assets/img/video-analytics-missing.svg";
import documentAndBoxURL from "@assets/img/document-and-box.svg";
import checklistWithXURL from "@assets/img/checklist-with-x.svg";
import lightBulbGreenCenterURL from "@assets/img/light-bulb-green-center.svg";
import eyeOpenLineUpURL from "@assets/img/eye-open-line-up.svg";
import playVideoIconURL from "@assets/img/play-video-icon.svg";
import uploadStatusCompleteURL from "@assets/img/upload-status-complete.svg";
import greenCheckCircleURL from "@assets/img/green-check-circle.svg";
import brandedURL from "@assets/img/product-badges/branded.svg";
import wishExpressURL from "@assets/img/product-badges/wish-express.svg";
import yellowBadgeURL from "@assets/img/product-badges/yellow-badge.svg";
import cleanImageURL from "@assets/img/product-badges/clean-image.svg";
import returnEnrolledURL from "@assets/img/product-badges/return-enrolled.svg";
import warningFilledWithBorderURL from "@assets/img/warning-filled-with-border.svg";
import selfieWithCodeURL from "@assets/img/selfie-with-code.svg";

import newWishLogoBlackURL from "@assets/img/rebranding/wish_logo_black.svg";
import newWishLogoWhiteURL from "@assets/img/rebranding/wish_logo_white.svg";
import newWishMerchantLogoCNURL from "@assets/img/rebranding/wish_merchant_logo_CN.svg";
import newWishMerchantLogoCZURL from "@assets/img/rebranding/wish_merchant_logo_CZ.svg";
import newWishMerchantLogoDEURL from "@assets/img/rebranding/wish_merchant_logo_DE.svg";
import newWishMerchantLogoENURL from "@assets/img/rebranding/wish_merchant_logo_EN.svg";
import newWishMerchantLogoESURL from "@assets/img/rebranding/wish_merchant_logo_ES.svg";
import newWishMerchantLogoFRURL from "@assets/img/rebranding/wish_merchant_logo_FR.svg";
import newWishMerchantLogoITURL from "@assets/img/rebranding/wish_merchant_logo_IT.svg";
import newWishMerchantLogoJPURL from "@assets/img/rebranding/wish_merchant_logo_JP.svg";
import newWishMerchantLogoKRURL from "@assets/img/rebranding/wish_merchant_logo_KR.svg";
import newWishMerchantLogoNLURL from "@assets/img/rebranding/wish_merchant_logo_NL.svg";
import newWishMerchantLogoPTURL from "@assets/img/rebranding/wish_merchant_logo_PT.svg";
import newWishMerchantLogoSEURL from "@assets/img/rebranding/wish_merchant_logo_SE.svg";
import newWishMerchantLogoTRURL from "@assets/img/rebranding/wish_merchant_logo_TR.svg";
import newWishMerchantLogoVNURL from "@assets/img/rebranding/wish_merchant_logo_VN.svg";
import newWishMerchantLogoWhiteCNURL from "@assets/img/rebranding/wish_merchant_logo_white_CN.svg";
import newWishMerchantLogoWhiteCZURL from "@assets/img/rebranding/wish_merchant_logo_white_CZ.svg";
import newWishMerchantLogoWhiteDEURL from "@assets/img/rebranding/wish_merchant_logo_white_DE.svg";
import newWishMerchantLogoWhiteENURL from "@assets/img/rebranding/wish_merchant_logo_white_EN.svg";
import newWishMerchantLogoWhiteESURL from "@assets/img/rebranding/wish_merchant_logo_white_ES.svg";
import newWishMerchantLogoWhiteFRURL from "@assets/img/rebranding/wish_merchant_logo_white_FR.svg";
import newWishMerchantLogoWhiteITURL from "@assets/img/rebranding/wish_merchant_logo_white_IT.svg";
import newWishMerchantLogoWhiteJPURL from "@assets/img/rebranding/wish_merchant_logo_white_JP.svg";
import newWishMerchantLogoWhiteKRURL from "@assets/img/rebranding/wish_merchant_logo_white_KR.svg";
import newWishMerchantLogoWhiteNLURL from "@assets/img/rebranding/wish_merchant_logo_white_NL.svg";
import newWishMerchantLogoWhitePTURL from "@assets/img/rebranding/wish_merchant_logo_white_PT.svg";
import newWishMerchantLogoWhiteSEURL from "@assets/img/rebranding/wish_merchant_logo_white_SE.svg";
import newWishMerchantLogoWhiteTRURL from "@assets/img/rebranding/wish_merchant_logo_white_TR.svg";
import newWishMerchantLogoWhiteVNURL from "@assets/img/rebranding/wish_merchant_logo_white_VN.svg";

import mmsWelcomeDesktopURL from "@assets/img/mms-welcome/mms-welcome-desktop.svg";
import mmsWelcomeUserTrafficURL from "@assets/img/mms-welcome/mms-welcome-user-traffic.svg";
import mmsWelcomePricingAdviceURL from "@assets/img/mms-welcome/mms-welcome-pricing-advice.svg";
import mmsWelcomeBusinessIntelligenceURL from "@assets/img/mms-welcome/mms-welcome-business-intelligence.svg";
import mmsWelcomeInventoryManagementURL from "@assets/img/mms-welcome/mms-welcome-inventory-management.svg";
import mmsWelcomeCustomerServiceURL from "@assets/img/mms-welcome/mms-welcome-customer-service.svg";
import mmsWelcomeProductVerificationURL from "@assets/img/mms-welcome/mms-welcome-product-verification.svg";
import mmsWelcomeLogisticsURL from "@assets/img/mms-welcome/mms-welcome-logistics.svg";
import mmsWelcomeContentCreationURL from "@assets/img/mms-welcome/mms-welcome-content-creation.svg";
import mmsWelcomeListingURL from "@assets/img/mms-welcome/mms-welcome-listing.svg";
import mmsWelcomeStoreSetupURL from "@assets/img/mms-welcome/mms-welcome-store-setup.svg";
import mmsWelcomeTreeURL from "@assets/img/mms-welcome/mms-welcome-tree.svg";
import mmsWelcomeTruckURL from "@assets/img/mms-welcome/mms-welcome-truck.svg";
import mmsWelcomeLaptopSurveyURL from "@assets/img/mms-welcome/mms-welcome-laptop-survey.svg";
import mmsWelcomeTicketsCoinsURL from "@assets/img/mms-welcome/mms-welcome-tickets-coins.svg";
import mmsWelcomePencilURL from "@assets/img/mms-welcome/mms-welcome-pencil.svg";
import mmsWelcomeSuccessBannerURL from "@assets/img/mms-welcome/mms-welcome-success-banner.svg";

export const customerSupport = customerSupportURL;
export const blueCheckmark = blueCheckmarkURL;
export const productsCloud = productsCloudURL;
export const storeShopper = storeShopperURL;
export const personUsingBinoculars = personUsingBinocularsURL;

export const adBadge = adBadgeURL;
export const wishAppTopBar = wishAppTopBarURL;
export const rocketPurpleBackground = rocketPurpleBackgroundURL;
export const wishExpressTruckSideways = wishExpressTruckSidewayskURL;
export const merchantPlusWishExpressHeader = merchantPlusWishExpressHeaderURL;
export const checkedEye = checkedEyeURL;
export const paymentCard = paymentCardURL;

export const crownGray = crownGrayURL;
export const clockCircleArrow = clockCircleArrowURL;
export const stackedBoxes = stackedBoxesURL;
export const confirmedDeliveryCheckmark = confirmedDeliveryCheckmarkURL;
export const laptopPlantBoxesHomescreenWish = laptopPlantBoxesHomescreenWishURL;
export const fulfillmentChecklistWithBox = fulfillmentChecklistWithBoxURL;
export const emptyImage = emptyImageURL;

export const notepadList = notepadListURL;
export const boxWithBlueRibbon = boxWithBlueRibbonURL;

export const productCatalog = productCatalogURL;
export const userOnPhoneLoveHandbag = userOnPhoneLoveHandbagURL;
export const yellowTruckBoxesInside = yellowTruckBoxesInsideURL;
export const plantLaptopHomeBox = plantLaptopHomeBoxURL;
export const houseWithPinpoints = houseWithPinpointsURL;

export const earlyPaymentEligibleBannerImg = earlyPaymentEligibleBannerImgURL;
export const earlyPaymentNotEligibleBannerImg =
  earlyPaymentNotEligibleBannerImgURL;
export const wishLogoInk = wishLogoInkURL;
export const developerDeskIllustration = developerDeskIllustrationURL;
export const developerMerchantsIllustration = developerMerchantsIllustrationURL;
export const developerNavigationIllustration =
  developerNavigationIllustrationURL;
export const developerLandingIllustration = developerLandingIllustrationURL;

export const appNoLogo = appNoLogoURL;
export const erpPartnerNoLogo = erpPartnerNoLogoURL;
export const shapesEmptyState = shapesEmptyStateURL;

export const settingsAppStoreBanner = settingsAppStoreBannerURL;
export const lockEmptyState = lockEmptyStateURL;

export const error403 = error403URL;
export const error404 = error404URL;
export const error500 = error500URL;

export const epcExplanationStep1 = epcExplanationStep1URL;
export const epcExplanationStep2 = epcExplanationStep2URL;
export const epcExplanationStep3 = epcExplanationStep3URL;

export const productBoostRocketHeartbreak = productBoostRocketHeartbreakURL;
export const productBoostRocket = productBoostRocketURL;

export const wishLogoBlue = wishLogoBlueURL;
export const wishLogoWhite = wishLogoWhiteURL;

export const perfHeader = perfHeaderURL;
export const blackArrowUp = blackArrowUpURL;
export const blackArrowDown = blackArrowDownURL;
export const greenArrowUp = greenArrowUpURL;
export const redArrowDown = redArrowDownURL;
export const gdecreaseArrow = gdecreaseArrowURL;
export const gincreaseArrow = gincreaseArrowURL;
export const rdecreaseArrow = rdecreaseArrowURL;
export const rincreaseArrow = rincreaseArrowURL;

export const cart = cartURL;
export const warehouse2 = warehouse2URL;
export const customer = customerURL;
export const awardFilled = awardFilledURL;
export const awardOutlined = awardOutlinedURL;

export const facebook = facebookURL;
export const facebookOutlined = facebookOutlinedURL;
export const facebookFilled = facebookFilledURL;
export const instagram = instagramURL;
export const instagramOutlined = instagramOutlinedURL;
export const instagramFilled = instagramFilledURL;
export const twitter = twitterURL;
export const twitterOutlined = twitterOutlinedURL;
export const twitterFilled = twitterFilledURL;
export const youtube = youtubeURL;
export const youtubeOutlined = youtubeOutlinedURL;
export const youtubeFilled = youtubeFilledURL;

export const lightBulbYellow = lightBulbYellowURL;
export const lightBulb = lightBulbURL;
export const lightBulbBackgroundColorYellow = lightBulbBackgroundColorYellowURL;
export const redBulb = redBulbURL;
export const palaceBlueBulb = palaceBlueBulbURL;
export const finesHeader = finesHeaderURL;
export const greenCheckmark = greenCheckmarkURL;
export const finesPolicyHeader = finesPolicyHeaderURL;
export const moneyIcon = moneyIconURL;

export const calculating = calculatingURL;
export const manCalculating = manCalculatingURL;
export const signature = signatureURL;
export const productBoostHeader = productBoostHeaderURL;
export const impressionBooster = impressionBoosterURL;
export const salesBooster = salesBoosterURL;
export const wishExpressTruck = wishExpressTruckURL;
export const wishExpressBlueBox = wishExpressBlueBoxURL;
export const activeMerchantStanding = activeMerchantStandingURL;
export const uploadProductIcon = uploadProductIconURL;
export const goldMerchantStanding = goldMerchantStandingURL;
export const platinumMerchantStanding = platinumMerchantStandingURL;
export const silverMerchantStanding = silverMerchantStandingURL;
export const underReviewMerchantStanding = underReviewMerchantStandingURL;
export const fbwHeader = fbwHeaderURL;
export const fbwDashboardHeader = fbwDashboardHeaderURL;
export const fbwShippingPriceDrop = fbwShippingPriceDropURL;
export const gmv = gmvURL;
export const order = orderURL;
export const sold = soldURL;
export const refunds = refundsURL;
export const refund = refundURL;
export const fbw = fbwURL;
export const fbw2 = fbw2Url;
export const lowInStock = lowInStockURL;
export const filter = filterURL;
export const filterBlue = filterBlueURL;
export const search = searchURL;
export const disputeSuccess = disputeSuccessURL;
export const disputeRejected = disputeRejectedURL;
export const disputePartiallyRejected = disputePartiallyRejectedURL;
export const submitDispute = submitDisputeURL;
export const productBoostDarkBlue = productBoostDarkBlueUrl;
export const productBoostTransaction = productBoostTransactionURL;
export const productBoostPhone = productBoostPhoneURL;
export const productBoostDetailHeader = productBoostDetailHeaderURL;
export const productBoostCampaignListHeader = productBoostCampaignListHeaderURL;
export const productBoostCampaignSpend = productBoostCampaignSpendURL;
export const productBoostSpendToGMV = productBoostSpendToGMVURL;
export const productBoostMaxBoost = productBoostMaxBoostURL;
export const productBoostBonusBudget = productBoostBonusBudgetURL;
export const productBoostHomepageModalLogo = productBoostHomepageModalLogoURL;
export const productBoostHomepageBudget = productBoostHomepageBudgetURL;
export const productBoostCostCalculationBanner =
  productBoostCostCalculationBannerURL;
export const cloudUpload = cloudUploadURL;
export const demoBoxCircle = demoBoxCircleURL;
export const phoneDimensionsCircle = phoneDimensionsCircleURL;
export const clockCircle = clockCircleURL;

export const productBoostKeywords = productBoostKeywordsURL;
export const wishExpressWithText = wishExpressWithTextURL;

export const illustration1 = illustration1URL;
export const illustration2 = illustration2URL;
export const illustration3 = illustration3URL;
export const illustration4 = illustration4URL;
export const illustration5 = illustration5URL;
export const illustration6 = illustration6URL;
export const cnmerchant1 = cnmerchant1URL;
export const cnmerchant2 = cnmerchant2URL;
export const merchant1 = merchant1URL;
export const merchant2 = merchant2URL;
export const merchant3 = merchant3URL;
export const merchant4 = merchant4URL;
export const lego = legoURL;
export const wishExpressWithoutText = wishExpressWithoutTextURL;

export const impressionIcon = impressionIconURL;
export const paidImpressionIcon = paidImpressionIconURL;
export const maxBoostImpressionIcon = maxBoostImpressionIconURL;
export const orderIcon = orderIconURL;
export const dollarIcon = dollarIconURL;
export const campaignIcon = campaignIconURL;
export const calendarIcon = calendarIconURL;
export const fulfillmentLogo = fulfillmentLogoURL;
export const createHeader = createHeaderURL;
export const addIcon = addIconURL;
export const recomIcon = recomIconURL;
export const fbwConfirm = fbwConfirmURL;
export const star = starURL;
export const bag = bagURL;
export const warehouse = warehouseURL;
export const fbwstep01 = fbwstep01URL;
export const fbwstep02 = fbwstep02URL;
export const fbwstep03 = fbwstep03URL;
export const fbwstep04 = fbwstep04URL;
export const fbwstep05 = fbwstep05URL;
export const fbwstep06 = fbwstep06URL;
export const fbwstep07 = fbwstep07URL;
export const fbwstep08 = fbwstep08URL;
export const fbwstep09 = fbwstep09URL;
export const wishForMerchants = wishForMerchantsURL;
export const laptopBagOfMoney = laptopBagOfMoneyURL;
export const quote = quoteURL;
export const merchantLanding = merchantLandingURL;
export const landingIllustrationLeft = landingIllustrationLeftURL;
export const landingIllustrationRight = landingIllustrationRightURL;
export const globalPhoneLocations = globalPhoneLocationsURL;
export const merchantLandingSmaller = merchantLandingSmallerURL;
export const epc = epcUrl;
export const epcFastPayments = epcFastPaymentsURL;
export const fbsIntro1 = fbsIntro1URL;
export const fbsIntro2 = fbsIntro2URL;
export const fbsIntro3 = fbsIntro3URL;
export const fbsPerformanceHeader = fbsPerformanceHeaderURL;
export const productBoostFBWFree = productBoostFBWFreeURL;
export const productBoostFBWDiscount = productBoostFBWDiscountURL;
export const whyFBS = whyFBSURL;
export const fbsEmptyState = fbsEmptyStateURL;
export const thirdPartyBrandedGoodsDeclaration =
  thirdPartyBrandedGoodsDeclarationURL;
export const returnsTruck = returnsTruckUrl;
export const returns = returnsURL;
export const coins = coinsURL;
export const advancedLogistics = advancedLogisticsUrl;
export const calendarBlue = calendarBlueURL;
export const wishPost = wishPostURL;
export const greyoutCoins = greyoutCoinsURL;
export const fbwInventoryListing = fbwInventoryListingURL;
export const fbwFee = fbwFeeURL;
export const paymentIcon = paymentIconURL;
export const cardTexture = cardTextureURL;
export const fbwRecommendationSection = fbwRecommendationSectionURL;
export const fbsRecommendationSection = fbsRecommendationSectionURL;
export const merchantInvitationHeader = merchantInvitationHeaderURL;
export const paypal = paypalUrl;
export const apiPartner = apiPartnerURL;
export const fourthlineLogoDark = fourthlineLogoDarkURL;
export const poweredByGoogle = poweredByGoogleURL;

export const trueBrandDirectoryHeader = trueBrandDirectoryHeaderURL;
export const merchantTrueBrandRequestsHeader =
  merchantTrueBrandRequestsHeaderURL;
export const absHeader = absHeaderURL;
export const brandedProductsHeader = brandedProductsHeaderURL;
export const brandedProductVerificationSection =
  brandedProductVerificationSectionURL;
export const policyArchiveHeader = policyArchiveHeaderURL;
export const productBoostSection = productBoostSectionURL;
export const brandDirectorySection = brandDirectorySectionURL;
export const absbSection = absbSectionURL;
export const gmvIcon = gmvIconURL;
export const ordersIcon = ordersIconURL;
export const impressionsIcon = impressionsIconURL;

export const verifyEmailIllustration = verifyEmailIllustrationURL;
export const verifyEmailBanner = verifyEmailBannerURL;
export const enrollBrandIllustration = enrollBrandIllustrationURL;
export const searchReportIllustration = searchReportIllustrationURL;

export const mainContentIllustration = mainContentIllustrationURL;
export const enforceBrandIcon = enforceBrandIconURL;
export const searchListingsIcon = searchListingsIconURL;
export const reportViolationsIcon = reportViolationsIconURL;

export const submitTrueBrandRequestConfirmation =
  submitTrueBrandRequestConfirmationURL;
export const ladyHoldingPackage = ladyHoldingPackageURL;
export const houseWithFlag = houseWithFlagURL;

export const reviewHeader = reviewHeaderURL;
export const resellerAgreement = resellerAgreementIllustrationURL;
export const womanUsingTelescope = womanUsingTelescopeURL;
export const idVerification = idVerificationURL;

export const blueWishHouse = blueWishHouseURL;
export const buildingsUnderDome = buildingsUnderDomeURL;
export const potentialUnlockedBanner = potentialUnlockedBannerURL;
export const computerPhoneOnDesk = computerPhoneOnDeskURL;
export const blueHouse = blueHouseURL;
export const blueHouseWithDecoration = blueHouseWithDecorationURL;
export const manHoldingBox = manHoldingBoxURL;
export const manHoldingId = manHoldingIdURL;
export const sizeChart = sizeChartURL;
export const sizeChartBannerImg = sizeChartBannerImgURL;
export const boxesInFrontOfEarth = boxesInFrontOfEarthURL;

export const merchantPlusHome = merchantPlusHomeURL;
export const merchantPlusAddProductsTask = merchantPlusAddProductsTaskURL;
export const merchantPlusUploadProductsHowTo =
  merchantPlusUploadProductsHowToURL;
export const merchantPlusVerifyEmailTask = merchantPlusVerifyEmailTaskURL;
export const merchantPlus2FATask = merchantPlus2FATaskURL;
export const merchantPlusSetupPaymentsTask = merchantPlusSetupPaymentsTaskURL;
export const merchantPlusSetupShippingTask = merchantPlusSetupShippingTaskURL;
export const merchantPlusMarkOrdersShippedTask =
  merchantPlusMarkOrdersShippedTaskURL;
export const merchantPlusSellerValidationTask =
  merchantPlusSellerValidationTaskURL;
export const merchantPlus2FAOn = merchantPlus2FAOnURL;
export const merchantPlusVacationModeOn = merchantPlusVacationModeOnURL;
export const merchantPlusVacationModeOff = merchantPlusVacationModeOffURL;
export const merchantPlusDeleteAllDevices = merchantPlusDeleteAllDevicesURL;
export const absbAuthorizedResellerIllustration =
  absbAuthorizedResellerIllustrationURL;
export const absbBrandOwnerIllustration = absbBrandOwnerIllustrationURL;
export const absbUnauthorizedResellerIllustration =
  absbUnauthorizedResellerIllustrationURL;

export const preorderOnboardingLogo = preorderOnboardingLogoURL;
export const preorderOnboardingContactLogo = preorderOnboardingContactLogoURL;
export const preorderProcessingOrderLogo = preorderProcessingOrderLogoURL;

export const restrictedProductPlantAndPlantSeedsRaw =
  restrictedProductPlantAndPlantSeedsRawURL;
export const restrictedProductVitaminsRaw = restrictedProductVitaminsRawURL;
export const restrictedProductBeveragesRaw = restrictedProductBeveragesRawURL;
export const restrictedProductFoodRaw = restrictedProductFoodRawURL;
export const restrictedProductPetFoodRaw = restrictedProductPetFoodRawURL;
export const restrictedProductMedicationsRaw =
  restrictedProductMedicationsRawURL;
export const restrictedProductCarSeatsRaw = restrictedProductCarSeatsRawURL;
export const restrictedProductCarriersRaw = restrictedProductCarriersRawURL;
export const restrictedProductSeatBeltRaw = restrictedProductSeatBeltRawURL;
export const restrictedProductWarrantiesRaw = restrictedProductWarrantiesRawURL;
export const restrictedProductPlantAndPlantSeedsCircle =
  restrictedProductPlantAndPlantSeedsCircleURL;
export const restrictedProductVitaminsCircle =
  restrictedProductVitaminsCircleURL;
export const restrictedProductBeveragesCircle =
  restrictedProductBeveragesCircleURL;
export const restrictedProductFoodCircle = restrictedProductFoodCircleURL;
export const restrictedProductPetFoodCircle = restrictedProductPetFoodCircleURL;
export const restrictedProductMedicationsCircle =
  restrictedProductMedicationsCircleURL;
export const restrictedProductCarSeatsCircle =
  restrictedProductCarSeatsCircleURL;
export const restrictedProductCarriersCircle =
  restrictedProductCarriersCircleURL;
export const restrictedProductSeatBeltCircle =
  restrictedProductSeatBeltCircleURL;
export const restrictedProductWarrantiesCircle =
  restrictedProductWarrantiesCircleURL;
export const restrictedProductPlantAndPlantSeedsColor =
  restrictedProductPlantAndPlantSeedsColorURL;
export const restrictedProductVitaminsColor = restrictedProductVitaminsColorURL;
export const restrictedProductBeveragesColor =
  restrictedProductBeveragesColorURL;
export const restrictedProductFoodColor = restrictedProductFoodColorURL;
export const restrictedProductPetFoodColor = restrictedProductPetFoodColorURL;
export const restrictedProductMedicationsColor =
  restrictedProductMedicationsColorURL;
export const restrictedProductCarSeatsColor = restrictedProductCarSeatsColorURL;
export const restrictedProductCarriersColor = restrictedProductCarriersColorURL;
export const restrictedProductSeatBeltColor = restrictedProductSeatBeltColorURL;
export const restrictedProductWarrantiesColor =
  restrictedProductWarrantiesColorURL;
export const restrictedProduct = restrictedProductURL;
export const weeklyDisbBannerImage = weeklyDisbBannerImageURL;
export const productUploadBannerImage = productUploadBannerImageURL;
export const productDemoBannerImage = productDemoBannerImageURL;

export const getItOnGooglePlay = getItOnGooglePlayURL;
export const downloadOnTheAppStore = downloadOnTheAppStoreURL;

export const darkCheckmark = darkCheckmarkURL;
export const whiteCheckmark = whiteCheckmarkURL;
export const close = closeURL;
export const closeWhiteRounded = closeWhiteRoundedURL;
export const thumbsUpDark = thumbsUpDarkURL;
export const thumbsUpWhite = thumbsUpWhiteURL;
export const thumbsDownDark = thumbsDownDarkURL;
export const thumbsDownWhite = thumbsDownWhiteURL;
export const externalLink = externalLinkURL;
export const paperAirplane = paperAirplaneURL;
export const locationMarker = locationMarkerURL;
export const editWishBlue = editWishBlueURL;
export const document = documentURL;
export const closedPackage = closedPackageURL;
export const truckOutline = truckOutlineURL;
export const boxes = boxesURL;
export const yellowExclamation = yellowExclamationURL;
export const warehouseOverviewBannerImage = warehouseOverviewBannerImageURL;
export const locationMarkerGrey = locationMarkerGreyURL;
export const locationMarkerYellow = locationMarkerYellowURL;
export const locationMarkerRed = locationMarkerRedURL;
export const redX = redXURL;
export const warningYellow = warningYellowURL;
export const refundAssurance = refundAssuranceURL;
export const socialAdsBoost = socialAdsBoostURL;
export const supportAgent = supportAgentURL;
export const starFilled = starFilledURL;
export const starUnfilled = starUnfilledURL;
export const starHalfFilled = starHalfFilledURL;
export const bannerUploadProducts = bannerUploadProductsURL;
export const bannerAddProductVariations = bannerAddProductVariationsURL;
export const performanceOverview = performanceOverviewURL;
export const grayTrash = grayTrashURL;
export const merchantCsHubHeader = merchantCsHubHeaderURL;
export const darkGreenCheckmark = darkGreenCheckmarkURL;
export const darkGreenCheckmarkFilled = darkGreenCheckmarkFilledURL;
export const grayDash = grayDashURL;
export const chevronRightBlue = chevronRightBlueURL;
export const cheeringEu = cheeringEuURL;
export const palaceBlueDispute = palaceBlueDisputeURL;
export const upsLogo = upsLogoURL;
export const mockMobileHeader = mockMobileHeaderURL;
export const productListingPlanHeader = productListingPlanHeaderURL;
export const productListingPlanAbout = productListingPlanAboutURL;
export const disable = disableURL;
export const shippingLabelBox = shippingLabelBoxURL;
export const shippingLabelEnvelope = shippingLabelEnvelopeURL;
export const uspsLogo = uspsLogoURL;
export const wssSplashRibbon = wssSplashRibbonURL;
export const wssSplashRibbonMobile = wssSplashRibbonMobileURL;
export const wssPlatinumBadge = wssPlatinumBadgeURL;
export const wssGoldBadge = wssGoldBadgeURL;
export const wssSilverBadge = wssSilverBadgeURL;
export const wssBronzeBadge = wssBronzeBadgeURL;
export const wssScreenshot = wssScreenshotURL;
export const wishAppImage = wishAppImageURL;
export const wishStandardsBanner = wishStandardsBannerURL;
export const wps = wpsURL;
export const warningFilled = warningFilledURL;
export const wssUnratedBadge = wssUnratedBadgeURL;
export const rightArrowLong = rightArrowLongURL;
export const badgeCheckmark = badgeCheckmarkURL;
export const merchantBlogBanner = merchantBlogBannerURL;
export const mfpHeader = mfpHeaderURL;
export const externalTwitter = externalTwitterURL;
export const externalFacebook = externalFacebookURL;
export const externalInstagram = externalInstagramURL;
export const externalPinterest = externalPinterestURL;
export const externalTiktok = externalTiktokURL;
export const externalYoutube = externalYoutubeURL;
export const externalLinkedin = externalLinkedinURL;
export const iconEnhancedPlatform = iconEnhancedPlatformURL;
export const iconGlobalSupport = iconGlobalSupportURL;
export const iconMerchantGrowthInitiatives = iconMerchantGrowthInitiativesURL;
export const iconWishCommunityPillars = iconWishCommunityPillarsURL;
export const iconWishFulfillment = iconWishFulfillmentURL;
export const iconWishInsights = iconWishInsightsURL;
export const iconWishStandards = iconWishStandardsURL;
export const logoEquick = logoEquickURL;
export const logoLianlianglobal = logoLianlianglobalURL;
export const logoSfinternational = logoSfinternationalURL;
export const logoSunyou = logoSunyouURL;
export const logoTopyou = logoTopyouURL;
export const logoUmf = logoUmfURL;
export const logoWiseexpress = logoWiseexpressURL;
export const logoYunexpress = logoYunexpressURL;
export const logoYwwenexpress = logoYwwenexpressURL;
export const headerMobile = headerMobileURL;
export const merchantConferenceCnBannerMobile =
  merchantConferenceCnBannerMobileURL;
export const videoBackgroundMobile = videoBackgroundMobileURL;
export const videoBackgroundMobileImage = videoBackgroundMobileImageURL;
export const summitBannerMobile = summitBannerMobileURL;
export const blueBackground = blueBackgroundURL;
export const footerBackground = footerBackgroundURL;
export const greyBackground = greyBackgroundURL;
export const headerImageWeb = headerImageWebURL;
export const summitBannerWeb = summitBannerWebURL;
export const videoBackgroundWeb = videoBackgroundWebURL;
export const merchantConferenceChinaBanner = merchantConferenceChinaBannerURL;
export const signupBackground = signupBackgroundURL;
export const videoBackgroundImageWeb = videoBackgroundImageWebURL;
export const teaserHeaderMobile = teaserHeaderMobileURL;
export const teaserHeader = teaserHeaderURL;
export const pictureDan = pictureDanURL;
export const pictureEmma = pictureEmmaURL;
export const pictureFarhang = pictureFarhangURL;
export const pictureSarah = pictureSarahURL;
export const pictureTarun = pictureTarunURL;
export const pictureVivian = pictureVivianURL;
export const topSeller = topSellerURL;
export const productCsvHeader = productCsvHeaderURL;
export const newProductPageBanner = newProductPageBannerURL;
export const w = wURL;
export const noActivePromotions = noActivePromotionsURL;
export const mfpCardBgDiscount = mfpCardBgDiscountURL;
export const mfpCardBgFlashSale = mfpCardBgFlashSaleURL;
export const lightningFilled = lightningFilledURL;
export const tagFilled = tagFilledURL;
export const tagFilledGrey = tagFilledGreyURL;
export const mfpPriceOnlyIllustration = mfpPriceOnlyIllustrationURL;
export const mfpHeaderIllustration = mfpHeaderIllustrationURL;
export const mfpHowToCreatePromotion = mfpHowToCreatePromotionURL;
export const mfpNeedMoreHelp = mfpNeedMoreHelpURL;
export const mfpNoPromotionsEver = mfpNoPromotionsEverURL;
export const mfpPriceOnlyExampleProductPicture = mfpPriceOnlyExampleProductURL;
export const qualifiedCarriers = qualifiedCarriersURL;
export const taxFormCalculator = taxFormCalculatorURL;
export const videoResourceHubBannerImage = videoResourceHubBannerImageURL;
export const videoManagementHubBannerImage = videoManagementHubBannerImageURL;
export const oneExclamation = oneExclamationURL;
export const twoExclamation = twoExclamationURL;
export const videoFilmBanner = videoFilmBannerURL;
export const videoFilmIcon = videoFilmIconURL;
export const holdingPhoneBanner = holdingPhoneBannerURL;
export const merchantFundedPromotions = merchantFundedPromotionsURL;
export const videos = videosURL;
export const wishStandards = wishStandardsURL;
export const blankWishClipExampleScreenshot = blankWishClipExampleScreenshotURL;
export const verticalOrientationCircleIcon = verticalOrientationCircleIconURL;
export const highResCircleIcon = highResCircleIconURL;
export const timerCircleIcon = timerCircleIconURL;
export const phoneCircleIcon = phoneCircleIconURL;
export const muteCircleIcon = muteCircleIconURL;
export const givingHandCircleIcon = givingHandCircleIconURL;
export const homeGettingImpressions = homeGettingImpressionsURL;
export const videoAnalyticsMissing = videoAnalyticsMissingURL;
export const documentAndBox = documentAndBoxURL;
export const checklistWithX = checklistWithXURL;
export const lightBulbGreenCenter = lightBulbGreenCenterURL;
export const eyeOpenLineUp = eyeOpenLineUpURL;
export const playVideoIcon = playVideoIconURL;
export const uploadStatusComplete = uploadStatusCompleteURL;
export const greenCheckCircle = greenCheckCircleURL;
export const branded = brandedURL;
export const wishExpress = wishExpressURL;
export const yellowBadge = yellowBadgeURL;
export const cleanImage = cleanImageURL;
export const returnEnrolled = returnEnrolledURL;
export const wishClipsBanner = wishClipsBannerURL;
export const warningFilledWithBorder = warningFilledWithBorderURL;
export const cnBusinessLicenseExample = cnBusinessLicenseExampleURL;
export const selfieWithCode = selfieWithCodeURL;
export const newWishLogoBlack = newWishLogoBlackURL;
export const newWishLogoWhite = newWishLogoWhiteURL;
export const newWishMerchantLogoCN = newWishMerchantLogoCNURL;
export const newWishMerchantLogoCZ = newWishMerchantLogoCZURL;
export const newWishMerchantLogoDE = newWishMerchantLogoDEURL;
export const newWishMerchantLogoEN = newWishMerchantLogoENURL;
export const newWishMerchantLogoES = newWishMerchantLogoESURL;
export const newWishMerchantLogoFR = newWishMerchantLogoFRURL;
export const newWishMerchantLogoIT = newWishMerchantLogoITURL;
export const newWishMerchantLogoJP = newWishMerchantLogoJPURL;
export const newWishMerchantLogoKR = newWishMerchantLogoKRURL;
export const newWishMerchantLogoNL = newWishMerchantLogoNLURL;
export const newWishMerchantLogoPT = newWishMerchantLogoPTURL;
export const newWishMerchantLogoSE = newWishMerchantLogoSEURL;
export const newWishMerchantLogoTR = newWishMerchantLogoTRURL;
export const newWishMerchantLogoVN = newWishMerchantLogoVNURL;
export const newWishMerchantLogoWhiteCN = newWishMerchantLogoWhiteCNURL;
export const newWishMerchantLogoWhiteCZ = newWishMerchantLogoWhiteCZURL;
export const newWishMerchantLogoWhiteDE = newWishMerchantLogoWhiteDEURL;
export const newWishMerchantLogoWhiteEN = newWishMerchantLogoWhiteENURL;
export const newWishMerchantLogoWhiteES = newWishMerchantLogoWhiteESURL;
export const newWishMerchantLogoWhiteFR = newWishMerchantLogoWhiteFRURL;
export const newWishMerchantLogoWhiteIT = newWishMerchantLogoWhiteITURL;
export const newWishMerchantLogoWhiteJP = newWishMerchantLogoWhiteJPURL;
export const newWishMerchantLogoWhiteKR = newWishMerchantLogoWhiteKRURL;
export const newWishMerchantLogoWhiteNL = newWishMerchantLogoWhiteNLURL;
export const newWishMerchantLogoWhitePT = newWishMerchantLogoWhitePTURL;
export const newWishMerchantLogoWhiteSE = newWishMerchantLogoWhiteSEURL;
export const newWishMerchantLogoWhiteTR = newWishMerchantLogoWhiteTRURL;
export const newWishMerchantLogoWhiteVN = newWishMerchantLogoWhiteVNURL;
export const mmsWelcomeDesktop = mmsWelcomeDesktopURL;
export const mmsWelcomeUserTraffic = mmsWelcomeUserTrafficURL;
export const mmsWelcomePricingAdvice = mmsWelcomePricingAdviceURL;
export const mmsWelcomeBusinessIntelligence = mmsWelcomeBusinessIntelligenceURL;
export const mmsWelcomeInventoryManagement = mmsWelcomeInventoryManagementURL;
export const mmsWelcomeCustomerService = mmsWelcomeCustomerServiceURL;
export const mmsWelcomeProductVerification = mmsWelcomeProductVerificationURL;
export const mmsWelcomeLogistics = mmsWelcomeLogisticsURL;
export const mmsWelcomeContentCreation = mmsWelcomeContentCreationURL;
export const mmsWelcomeListing = mmsWelcomeListingURL;
export const mmsWelcomeStoreSetup = mmsWelcomeStoreSetupURL;
export const mmsWelcomeTree = mmsWelcomeTreeURL;
export const mmsWelcomeTruck = mmsWelcomeTruckURL;
export const mmsWelcomeLaptopSurvey = mmsWelcomeLaptopSurveyURL;
export const mmsWelcomeTicketsCoins = mmsWelcomeTicketsCoinsURL;
export const mmsWelcomePencil = mmsWelcomePencilURL;
export const mmsWelcomeSuccessBanner = mmsWelcomeSuccessBannerURL;
